// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CAJNPBEFLHF.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from CAJNPBEFLHF.proto</summary>
  public static partial class CAJNPBEFLHFReflection {

    #region Descriptor
    /// <summary>File descriptor for CAJNPBEFLHF.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CAJNPBEFLHFReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFDQUpOUEJFRkxIRi5wcm90byqEAwoLQ0FKTlBCRUZMSEYSHwobUk9HVUVf",
            "QlVGRl9TT1VSQ0VfVFlQRV9OT05FEAASIQodUk9HVUVfQlVGRl9TT1VSQ0Vf",
            "VFlQRV9TRUxFQ1QQARIiCh5ST0dVRV9CVUZGX1NPVVJDRV9UWVBFX0VOSEFO",
            "Q0UQAhIiCh5ST0dVRV9CVUZGX1NPVVJDRV9UWVBFX01JUkFDTEUQAxIjCh9S",
            "T0dVRV9CVUZGX1NPVVJDRV9UWVBFX0RJQUxPR1VFEAQSIAocUk9HVUVfQlVG",
            "Rl9TT1VSQ0VfVFlQRV9CT05VUxAFEiUKIVJPR1VFX0JVRkZfU09VUkNFX1RZ",
            "UEVfTUFaRV9TS0lMTBAGEh8KG1JPR1VFX0JVRkZfU09VUkNFX1RZUEVfU0hP",
            "UBAHEioKJlJPR1VFX0JVRkZfU09VUkNFX1RZUEVfTEVWRUxfTUVDSEFOSVNN",
            "EAgSLgoqUk9HVUVfQlVGRl9TT1VSQ0VfVFlQRV9FTkRMRVNTX0xFVkVMX1NU",
            "QVJUEAlCHqoCG0VnZ0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EggLink.DanhengServer.Proto.CAJNPBEFLHF), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CAJNPBEFLHF {
    [pbr::OriginalName("ROGUE_BUFF_SOURCE_TYPE_NONE")] RogueBuffSourceTypeNone = 0,
    [pbr::OriginalName("ROGUE_BUFF_SOURCE_TYPE_SELECT")] RogueBuffSourceTypeSelect = 1,
    [pbr::OriginalName("ROGUE_BUFF_SOURCE_TYPE_ENHANCE")] RogueBuffSourceTypeEnhance = 2,
    [pbr::OriginalName("ROGUE_BUFF_SOURCE_TYPE_MIRACLE")] RogueBuffSourceTypeMiracle = 3,
    [pbr::OriginalName("ROGUE_BUFF_SOURCE_TYPE_DIALOGUE")] RogueBuffSourceTypeDialogue = 4,
    [pbr::OriginalName("ROGUE_BUFF_SOURCE_TYPE_BONUS")] RogueBuffSourceTypeBonus = 5,
    [pbr::OriginalName("ROGUE_BUFF_SOURCE_TYPE_MAZE_SKILL")] RogueBuffSourceTypeMazeSkill = 6,
    [pbr::OriginalName("ROGUE_BUFF_SOURCE_TYPE_SHOP")] RogueBuffSourceTypeShop = 7,
    [pbr::OriginalName("ROGUE_BUFF_SOURCE_TYPE_LEVEL_MECHANISM")] RogueBuffSourceTypeLevelMechanism = 8,
    [pbr::OriginalName("ROGUE_BUFF_SOURCE_TYPE_ENDLESS_LEVEL_START")] RogueBuffSourceTypeEndlessLevelStart = 9,
  }

  #endregion

}

#endregion Designer generated code
