// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OGHKAGEDFGH.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from OGHKAGEDFGH.proto</summary>
  public static partial class OGHKAGEDFGHReflection {

    #region Descriptor
    /// <summary>File descriptor for OGHKAGEDFGH.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OGHKAGEDFGHReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFPR0hLQUdFREZHSC5wcm90byJQCgtPR0hLQUdFREZHSBITCgtOQlBGT0FB",
            "RkNBThgIIAMoDRIPCgdjb25maXJtGAwgASgIEhsKE3NlbGVjdF9jZWxsX2lk",
            "X2xpc3QYDSABKA1CHqoCG0VnZ0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.OGHKAGEDFGH), global::EggLink.DanhengServer.Proto.OGHKAGEDFGH.Parser, new[]{ "NBPFOAAFCAN", "Confirm", "SelectCellIdList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OGHKAGEDFGH : pb::IMessage<OGHKAGEDFGH>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OGHKAGEDFGH> _parser = new pb::MessageParser<OGHKAGEDFGH>(() => new OGHKAGEDFGH());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OGHKAGEDFGH> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.OGHKAGEDFGHReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OGHKAGEDFGH() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OGHKAGEDFGH(OGHKAGEDFGH other) : this() {
      nBPFOAAFCAN_ = other.nBPFOAAFCAN_.Clone();
      confirm_ = other.confirm_;
      selectCellIdList_ = other.selectCellIdList_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OGHKAGEDFGH Clone() {
      return new OGHKAGEDFGH(this);
    }

    /// <summary>Field number for the "NBPFOAAFCAN" field.</summary>
    public const int NBPFOAAFCANFieldNumber = 8;
    private static readonly pb::FieldCodec<uint> _repeated_nBPFOAAFCAN_codec
        = pb::FieldCodec.ForUInt32(66);
    private readonly pbc::RepeatedField<uint> nBPFOAAFCAN_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> NBPFOAAFCAN {
      get { return nBPFOAAFCAN_; }
    }

    /// <summary>Field number for the "confirm" field.</summary>
    public const int ConfirmFieldNumber = 12;
    private bool confirm_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Confirm {
      get { return confirm_; }
      set {
        confirm_ = value;
      }
    }

    /// <summary>Field number for the "select_cell_id_list" field.</summary>
    public const int SelectCellIdListFieldNumber = 13;
    private uint selectCellIdList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SelectCellIdList {
      get { return selectCellIdList_; }
      set {
        selectCellIdList_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OGHKAGEDFGH);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OGHKAGEDFGH other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!nBPFOAAFCAN_.Equals(other.nBPFOAAFCAN_)) return false;
      if (Confirm != other.Confirm) return false;
      if (SelectCellIdList != other.SelectCellIdList) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= nBPFOAAFCAN_.GetHashCode();
      if (Confirm != false) hash ^= Confirm.GetHashCode();
      if (SelectCellIdList != 0) hash ^= SelectCellIdList.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      nBPFOAAFCAN_.WriteTo(output, _repeated_nBPFOAAFCAN_codec);
      if (Confirm != false) {
        output.WriteRawTag(96);
        output.WriteBool(Confirm);
      }
      if (SelectCellIdList != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(SelectCellIdList);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      nBPFOAAFCAN_.WriteTo(ref output, _repeated_nBPFOAAFCAN_codec);
      if (Confirm != false) {
        output.WriteRawTag(96);
        output.WriteBool(Confirm);
      }
      if (SelectCellIdList != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(SelectCellIdList);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += nBPFOAAFCAN_.CalculateSize(_repeated_nBPFOAAFCAN_codec);
      if (Confirm != false) {
        size += 1 + 1;
      }
      if (SelectCellIdList != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SelectCellIdList);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OGHKAGEDFGH other) {
      if (other == null) {
        return;
      }
      nBPFOAAFCAN_.Add(other.nBPFOAAFCAN_);
      if (other.Confirm != false) {
        Confirm = other.Confirm;
      }
      if (other.SelectCellIdList != 0) {
        SelectCellIdList = other.SelectCellIdList;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 66:
          case 64: {
            nBPFOAAFCAN_.AddEntriesFrom(input, _repeated_nBPFOAAFCAN_codec);
            break;
          }
          case 96: {
            Confirm = input.ReadBool();
            break;
          }
          case 104: {
            SelectCellIdList = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 66:
          case 64: {
            nBPFOAAFCAN_.AddEntriesFrom(ref input, _repeated_nBPFOAAFCAN_codec);
            break;
          }
          case 96: {
            Confirm = input.ReadBool();
            break;
          }
          case 104: {
            SelectCellIdList = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
