// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EvolveBuildFinishScNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from EvolveBuildFinishScNotify.proto</summary>
  public static partial class EvolveBuildFinishScNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for EvolveBuildFinishScNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EvolveBuildFinishScNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9Fdm9sdmVCdWlsZEZpbmlzaFNjTm90aWZ5LnByb3RvGhFIQkhESUdPUERN",
            "UC5wcm90bxoaRXZvbHZlQnVpbGRMZXZlbEluZm8ucHJvdG8i3QEKGUV2b2x2",
            "ZUJ1aWxkRmluaXNoU2NOb3RpZnkSJgoQQmF0dGxlUmVzdWx0VHlwZRgPIAEo",
            "DjIMLkhCSERJR09QRE1QEgwKBENvaW4YBiABKA0SDQoFU2NvcmUYBSABKA0S",
            "DgoGSXNMb3NlGAggASgIEgwKBFdhdmUYCiABKA0SKAoJTGV2ZWxJbmZvGAMg",
            "ASgLMhUuRXZvbHZlQnVpbGRMZXZlbEluZm8SCwoDRXhwGAsgASgNEg8KB0xl",
            "dmVsSWQYASABKA0SFQoNQ3VyUGVyaW9kVHlwZRgEIAEoDUIeqgIbRWdnTGlu",
            "ay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.HBHDIGOPDMPReflection.Descriptor, global::EggLink.DanhengServer.Proto.EvolveBuildLevelInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.EvolveBuildFinishScNotify), global::EggLink.DanhengServer.Proto.EvolveBuildFinishScNotify.Parser, new[]{ "BattleResultType", "Coin", "Score", "IsLose", "Wave", "LevelInfo", "Exp", "LevelId", "CurPeriodType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EvolveBuildFinishScNotify : pb::IMessage<EvolveBuildFinishScNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EvolveBuildFinishScNotify> _parser = new pb::MessageParser<EvolveBuildFinishScNotify>(() => new EvolveBuildFinishScNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EvolveBuildFinishScNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.EvolveBuildFinishScNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EvolveBuildFinishScNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EvolveBuildFinishScNotify(EvolveBuildFinishScNotify other) : this() {
      battleResultType_ = other.battleResultType_;
      coin_ = other.coin_;
      score_ = other.score_;
      isLose_ = other.isLose_;
      wave_ = other.wave_;
      levelInfo_ = other.levelInfo_ != null ? other.levelInfo_.Clone() : null;
      exp_ = other.exp_;
      levelId_ = other.levelId_;
      curPeriodType_ = other.curPeriodType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EvolveBuildFinishScNotify Clone() {
      return new EvolveBuildFinishScNotify(this);
    }

    /// <summary>Field number for the "BattleResultType" field.</summary>
    public const int BattleResultTypeFieldNumber = 15;
    private global::EggLink.DanhengServer.Proto.HBHDIGOPDMP battleResultType_ = global::EggLink.DanhengServer.Proto.HBHDIGOPDMP.EvolveBattleResultNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.HBHDIGOPDMP BattleResultType {
      get { return battleResultType_; }
      set {
        battleResultType_ = value;
      }
    }

    /// <summary>Field number for the "Coin" field.</summary>
    public const int CoinFieldNumber = 6;
    private uint coin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Coin {
      get { return coin_; }
      set {
        coin_ = value;
      }
    }

    /// <summary>Field number for the "Score" field.</summary>
    public const int ScoreFieldNumber = 5;
    private uint score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    /// <summary>Field number for the "IsLose" field.</summary>
    public const int IsLoseFieldNumber = 8;
    private bool isLose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsLose {
      get { return isLose_; }
      set {
        isLose_ = value;
      }
    }

    /// <summary>Field number for the "Wave" field.</summary>
    public const int WaveFieldNumber = 10;
    private uint wave_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Wave {
      get { return wave_; }
      set {
        wave_ = value;
      }
    }

    /// <summary>Field number for the "LevelInfo" field.</summary>
    public const int LevelInfoFieldNumber = 3;
    private global::EggLink.DanhengServer.Proto.EvolveBuildLevelInfo levelInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.EvolveBuildLevelInfo LevelInfo {
      get { return levelInfo_; }
      set {
        levelInfo_ = value;
      }
    }

    /// <summary>Field number for the "Exp" field.</summary>
    public const int ExpFieldNumber = 11;
    private uint exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    /// <summary>Field number for the "LevelId" field.</summary>
    public const int LevelIdFieldNumber = 1;
    private uint levelId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LevelId {
      get { return levelId_; }
      set {
        levelId_ = value;
      }
    }

    /// <summary>Field number for the "CurPeriodType" field.</summary>
    public const int CurPeriodTypeFieldNumber = 4;
    private uint curPeriodType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CurPeriodType {
      get { return curPeriodType_; }
      set {
        curPeriodType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EvolveBuildFinishScNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EvolveBuildFinishScNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BattleResultType != other.BattleResultType) return false;
      if (Coin != other.Coin) return false;
      if (Score != other.Score) return false;
      if (IsLose != other.IsLose) return false;
      if (Wave != other.Wave) return false;
      if (!object.Equals(LevelInfo, other.LevelInfo)) return false;
      if (Exp != other.Exp) return false;
      if (LevelId != other.LevelId) return false;
      if (CurPeriodType != other.CurPeriodType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BattleResultType != global::EggLink.DanhengServer.Proto.HBHDIGOPDMP.EvolveBattleResultNone) hash ^= BattleResultType.GetHashCode();
      if (Coin != 0) hash ^= Coin.GetHashCode();
      if (Score != 0) hash ^= Score.GetHashCode();
      if (IsLose != false) hash ^= IsLose.GetHashCode();
      if (Wave != 0) hash ^= Wave.GetHashCode();
      if (levelInfo_ != null) hash ^= LevelInfo.GetHashCode();
      if (Exp != 0) hash ^= Exp.GetHashCode();
      if (LevelId != 0) hash ^= LevelId.GetHashCode();
      if (CurPeriodType != 0) hash ^= CurPeriodType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LevelId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(LevelId);
      }
      if (levelInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LevelInfo);
      }
      if (CurPeriodType != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(CurPeriodType);
      }
      if (Score != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Score);
      }
      if (Coin != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Coin);
      }
      if (IsLose != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsLose);
      }
      if (Wave != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(Wave);
      }
      if (Exp != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(Exp);
      }
      if (BattleResultType != global::EggLink.DanhengServer.Proto.HBHDIGOPDMP.EvolveBattleResultNone) {
        output.WriteRawTag(120);
        output.WriteEnum((int) BattleResultType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LevelId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(LevelId);
      }
      if (levelInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LevelInfo);
      }
      if (CurPeriodType != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(CurPeriodType);
      }
      if (Score != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Score);
      }
      if (Coin != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Coin);
      }
      if (IsLose != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsLose);
      }
      if (Wave != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(Wave);
      }
      if (Exp != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(Exp);
      }
      if (BattleResultType != global::EggLink.DanhengServer.Proto.HBHDIGOPDMP.EvolveBattleResultNone) {
        output.WriteRawTag(120);
        output.WriteEnum((int) BattleResultType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BattleResultType != global::EggLink.DanhengServer.Proto.HBHDIGOPDMP.EvolveBattleResultNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BattleResultType);
      }
      if (Coin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Coin);
      }
      if (Score != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Score);
      }
      if (IsLose != false) {
        size += 1 + 1;
      }
      if (Wave != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Wave);
      }
      if (levelInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LevelInfo);
      }
      if (Exp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Exp);
      }
      if (LevelId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LevelId);
      }
      if (CurPeriodType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurPeriodType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EvolveBuildFinishScNotify other) {
      if (other == null) {
        return;
      }
      if (other.BattleResultType != global::EggLink.DanhengServer.Proto.HBHDIGOPDMP.EvolveBattleResultNone) {
        BattleResultType = other.BattleResultType;
      }
      if (other.Coin != 0) {
        Coin = other.Coin;
      }
      if (other.Score != 0) {
        Score = other.Score;
      }
      if (other.IsLose != false) {
        IsLose = other.IsLose;
      }
      if (other.Wave != 0) {
        Wave = other.Wave;
      }
      if (other.levelInfo_ != null) {
        if (levelInfo_ == null) {
          LevelInfo = new global::EggLink.DanhengServer.Proto.EvolveBuildLevelInfo();
        }
        LevelInfo.MergeFrom(other.LevelInfo);
      }
      if (other.Exp != 0) {
        Exp = other.Exp;
      }
      if (other.LevelId != 0) {
        LevelId = other.LevelId;
      }
      if (other.CurPeriodType != 0) {
        CurPeriodType = other.CurPeriodType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LevelId = input.ReadUInt32();
            break;
          }
          case 26: {
            if (levelInfo_ == null) {
              LevelInfo = new global::EggLink.DanhengServer.Proto.EvolveBuildLevelInfo();
            }
            input.ReadMessage(LevelInfo);
            break;
          }
          case 32: {
            CurPeriodType = input.ReadUInt32();
            break;
          }
          case 40: {
            Score = input.ReadUInt32();
            break;
          }
          case 48: {
            Coin = input.ReadUInt32();
            break;
          }
          case 64: {
            IsLose = input.ReadBool();
            break;
          }
          case 80: {
            Wave = input.ReadUInt32();
            break;
          }
          case 88: {
            Exp = input.ReadUInt32();
            break;
          }
          case 120: {
            BattleResultType = (global::EggLink.DanhengServer.Proto.HBHDIGOPDMP) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LevelId = input.ReadUInt32();
            break;
          }
          case 26: {
            if (levelInfo_ == null) {
              LevelInfo = new global::EggLink.DanhengServer.Proto.EvolveBuildLevelInfo();
            }
            input.ReadMessage(LevelInfo);
            break;
          }
          case 32: {
            CurPeriodType = input.ReadUInt32();
            break;
          }
          case 40: {
            Score = input.ReadUInt32();
            break;
          }
          case 48: {
            Coin = input.ReadUInt32();
            break;
          }
          case 64: {
            IsLose = input.ReadBool();
            break;
          }
          case 80: {
            Wave = input.ReadUInt32();
            break;
          }
          case 88: {
            Exp = input.ReadUInt32();
            break;
          }
          case 120: {
            BattleResultType = (global::EggLink.DanhengServer.Proto.HBHDIGOPDMP) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
