// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FHHDICEEHOE.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from FHHDICEEHOE.proto</summary>
  public static partial class FHHDICEEHOEReflection {

    #region Descriptor
    /// <summary>File descriptor for FHHDICEEHOE.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FHHDICEEHOEReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFGSEhESUNFRUhPRS5wcm90byKNAQoLRkhIRElDRUVIT0USEwoLQU9FRklI",
            "QkJBR0UYASADKA0SEwoLRE9FS1BHTE5LRkIYDCABKAgSEwoLTElCS0xEQUxI",
            "SlAYDSABKA0SFAoMdG90YWxfZGFtYWdlGAkgASgBEhMKC0lBRkZMTkZQTEpD",
            "GAogASgIEhQKDGZpbmlzaF9sZXZlbBgDIAEoDUIeqgIbRWdnTGluay5EYW5o",
            "ZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.FHHDICEEHOE), global::EggLink.DanhengServer.Proto.FHHDICEEHOE.Parser, new[]{ "AOEFIHBBAGE", "DOEKPGLNKFB", "LIBKLDALHJP", "TotalDamage", "IAFFLNFPLJC", "FinishLevel" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FHHDICEEHOE : pb::IMessage<FHHDICEEHOE>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FHHDICEEHOE> _parser = new pb::MessageParser<FHHDICEEHOE>(() => new FHHDICEEHOE());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FHHDICEEHOE> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.FHHDICEEHOEReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FHHDICEEHOE() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FHHDICEEHOE(FHHDICEEHOE other) : this() {
      aOEFIHBBAGE_ = other.aOEFIHBBAGE_.Clone();
      dOEKPGLNKFB_ = other.dOEKPGLNKFB_;
      lIBKLDALHJP_ = other.lIBKLDALHJP_;
      totalDamage_ = other.totalDamage_;
      iAFFLNFPLJC_ = other.iAFFLNFPLJC_;
      finishLevel_ = other.finishLevel_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FHHDICEEHOE Clone() {
      return new FHHDICEEHOE(this);
    }

    /// <summary>Field number for the "AOEFIHBBAGE" field.</summary>
    public const int AOEFIHBBAGEFieldNumber = 1;
    private static readonly pb::FieldCodec<uint> _repeated_aOEFIHBBAGE_codec
        = pb::FieldCodec.ForUInt32(10);
    private readonly pbc::RepeatedField<uint> aOEFIHBBAGE_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> AOEFIHBBAGE {
      get { return aOEFIHBBAGE_; }
    }

    /// <summary>Field number for the "DOEKPGLNKFB" field.</summary>
    public const int DOEKPGLNKFBFieldNumber = 12;
    private bool dOEKPGLNKFB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DOEKPGLNKFB {
      get { return dOEKPGLNKFB_; }
      set {
        dOEKPGLNKFB_ = value;
      }
    }

    /// <summary>Field number for the "LIBKLDALHJP" field.</summary>
    public const int LIBKLDALHJPFieldNumber = 13;
    private uint lIBKLDALHJP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LIBKLDALHJP {
      get { return lIBKLDALHJP_; }
      set {
        lIBKLDALHJP_ = value;
      }
    }

    /// <summary>Field number for the "total_damage" field.</summary>
    public const int TotalDamageFieldNumber = 9;
    private double totalDamage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TotalDamage {
      get { return totalDamage_; }
      set {
        totalDamage_ = value;
      }
    }

    /// <summary>Field number for the "IAFFLNFPLJC" field.</summary>
    public const int IAFFLNFPLJCFieldNumber = 10;
    private bool iAFFLNFPLJC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IAFFLNFPLJC {
      get { return iAFFLNFPLJC_; }
      set {
        iAFFLNFPLJC_ = value;
      }
    }

    /// <summary>Field number for the "finish_level" field.</summary>
    public const int FinishLevelFieldNumber = 3;
    private uint finishLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FinishLevel {
      get { return finishLevel_; }
      set {
        finishLevel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FHHDICEEHOE);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FHHDICEEHOE other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!aOEFIHBBAGE_.Equals(other.aOEFIHBBAGE_)) return false;
      if (DOEKPGLNKFB != other.DOEKPGLNKFB) return false;
      if (LIBKLDALHJP != other.LIBKLDALHJP) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TotalDamage, other.TotalDamage)) return false;
      if (IAFFLNFPLJC != other.IAFFLNFPLJC) return false;
      if (FinishLevel != other.FinishLevel) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= aOEFIHBBAGE_.GetHashCode();
      if (DOEKPGLNKFB != false) hash ^= DOEKPGLNKFB.GetHashCode();
      if (LIBKLDALHJP != 0) hash ^= LIBKLDALHJP.GetHashCode();
      if (TotalDamage != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TotalDamage);
      if (IAFFLNFPLJC != false) hash ^= IAFFLNFPLJC.GetHashCode();
      if (FinishLevel != 0) hash ^= FinishLevel.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      aOEFIHBBAGE_.WriteTo(output, _repeated_aOEFIHBBAGE_codec);
      if (FinishLevel != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(FinishLevel);
      }
      if (TotalDamage != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(TotalDamage);
      }
      if (IAFFLNFPLJC != false) {
        output.WriteRawTag(80);
        output.WriteBool(IAFFLNFPLJC);
      }
      if (DOEKPGLNKFB != false) {
        output.WriteRawTag(96);
        output.WriteBool(DOEKPGLNKFB);
      }
      if (LIBKLDALHJP != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(LIBKLDALHJP);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      aOEFIHBBAGE_.WriteTo(ref output, _repeated_aOEFIHBBAGE_codec);
      if (FinishLevel != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(FinishLevel);
      }
      if (TotalDamage != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(TotalDamage);
      }
      if (IAFFLNFPLJC != false) {
        output.WriteRawTag(80);
        output.WriteBool(IAFFLNFPLJC);
      }
      if (DOEKPGLNKFB != false) {
        output.WriteRawTag(96);
        output.WriteBool(DOEKPGLNKFB);
      }
      if (LIBKLDALHJP != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(LIBKLDALHJP);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += aOEFIHBBAGE_.CalculateSize(_repeated_aOEFIHBBAGE_codec);
      if (DOEKPGLNKFB != false) {
        size += 1 + 1;
      }
      if (LIBKLDALHJP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LIBKLDALHJP);
      }
      if (TotalDamage != 0D) {
        size += 1 + 8;
      }
      if (IAFFLNFPLJC != false) {
        size += 1 + 1;
      }
      if (FinishLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FinishLevel);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FHHDICEEHOE other) {
      if (other == null) {
        return;
      }
      aOEFIHBBAGE_.Add(other.aOEFIHBBAGE_);
      if (other.DOEKPGLNKFB != false) {
        DOEKPGLNKFB = other.DOEKPGLNKFB;
      }
      if (other.LIBKLDALHJP != 0) {
        LIBKLDALHJP = other.LIBKLDALHJP;
      }
      if (other.TotalDamage != 0D) {
        TotalDamage = other.TotalDamage;
      }
      if (other.IAFFLNFPLJC != false) {
        IAFFLNFPLJC = other.IAFFLNFPLJC;
      }
      if (other.FinishLevel != 0) {
        FinishLevel = other.FinishLevel;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            aOEFIHBBAGE_.AddEntriesFrom(input, _repeated_aOEFIHBBAGE_codec);
            break;
          }
          case 24: {
            FinishLevel = input.ReadUInt32();
            break;
          }
          case 73: {
            TotalDamage = input.ReadDouble();
            break;
          }
          case 80: {
            IAFFLNFPLJC = input.ReadBool();
            break;
          }
          case 96: {
            DOEKPGLNKFB = input.ReadBool();
            break;
          }
          case 104: {
            LIBKLDALHJP = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            aOEFIHBBAGE_.AddEntriesFrom(ref input, _repeated_aOEFIHBBAGE_codec);
            break;
          }
          case 24: {
            FinishLevel = input.ReadUInt32();
            break;
          }
          case 73: {
            TotalDamage = input.ReadDouble();
            break;
          }
          case 80: {
            IAFFLNFPLJC = input.ReadBool();
            break;
          }
          case 96: {
            DOEKPGLNKFB = input.ReadBool();
            break;
          }
          case 104: {
            LIBKLDALHJP = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
