// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetAetherDivideChallengeInfoScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from GetAetherDivideChallengeInfoScRsp.proto</summary>
  public static partial class GetAetherDivideChallengeInfoScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for GetAetherDivideChallengeInfoScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetAetherDivideChallengeInfoScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidHZXRBZXRoZXJEaXZpZGVDaGFsbGVuZ2VJbmZvU2NSc3AucHJvdG8icwoh",
            "R2V0QWV0aGVyRGl2aWRlQ2hhbGxlbmdlSW5mb1NjUnNwEhMKC01FRk5KS09G",
            "TE5EGAUgAygNEg8KB3JldGNvZGUYCiABKA0SEwoLS0RJQUZFTUxFT0UYByAB",
            "KA0SEwoLQUdDQkNPQlBHTUYYDiADKA1CHqoCG0VnZ0xpbmsuRGFuaGVuZ1Nl",
            "cnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.GetAetherDivideChallengeInfoScRsp), global::EggLink.DanhengServer.Proto.GetAetherDivideChallengeInfoScRsp.Parser, new[]{ "MEFNJKOFLND", "Retcode", "KDIAFEMLEOE", "AGCBCOBPGMF" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetAetherDivideChallengeInfoScRsp : pb::IMessage<GetAetherDivideChallengeInfoScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetAetherDivideChallengeInfoScRsp> _parser = new pb::MessageParser<GetAetherDivideChallengeInfoScRsp>(() => new GetAetherDivideChallengeInfoScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetAetherDivideChallengeInfoScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.GetAetherDivideChallengeInfoScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetAetherDivideChallengeInfoScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetAetherDivideChallengeInfoScRsp(GetAetherDivideChallengeInfoScRsp other) : this() {
      mEFNJKOFLND_ = other.mEFNJKOFLND_.Clone();
      retcode_ = other.retcode_;
      kDIAFEMLEOE_ = other.kDIAFEMLEOE_;
      aGCBCOBPGMF_ = other.aGCBCOBPGMF_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetAetherDivideChallengeInfoScRsp Clone() {
      return new GetAetherDivideChallengeInfoScRsp(this);
    }

    /// <summary>Field number for the "MEFNJKOFLND" field.</summary>
    public const int MEFNJKOFLNDFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_mEFNJKOFLND_codec
        = pb::FieldCodec.ForUInt32(42);
    private readonly pbc::RepeatedField<uint> mEFNJKOFLND_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> MEFNJKOFLND {
      get { return mEFNJKOFLND_; }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 10;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "KDIAFEMLEOE" field.</summary>
    public const int KDIAFEMLEOEFieldNumber = 7;
    private uint kDIAFEMLEOE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KDIAFEMLEOE {
      get { return kDIAFEMLEOE_; }
      set {
        kDIAFEMLEOE_ = value;
      }
    }

    /// <summary>Field number for the "AGCBCOBPGMF" field.</summary>
    public const int AGCBCOBPGMFFieldNumber = 14;
    private static readonly pb::FieldCodec<uint> _repeated_aGCBCOBPGMF_codec
        = pb::FieldCodec.ForUInt32(114);
    private readonly pbc::RepeatedField<uint> aGCBCOBPGMF_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> AGCBCOBPGMF {
      get { return aGCBCOBPGMF_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetAetherDivideChallengeInfoScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetAetherDivideChallengeInfoScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!mEFNJKOFLND_.Equals(other.mEFNJKOFLND_)) return false;
      if (Retcode != other.Retcode) return false;
      if (KDIAFEMLEOE != other.KDIAFEMLEOE) return false;
      if(!aGCBCOBPGMF_.Equals(other.aGCBCOBPGMF_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= mEFNJKOFLND_.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (KDIAFEMLEOE != 0) hash ^= KDIAFEMLEOE.GetHashCode();
      hash ^= aGCBCOBPGMF_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      mEFNJKOFLND_.WriteTo(output, _repeated_mEFNJKOFLND_codec);
      if (KDIAFEMLEOE != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(KDIAFEMLEOE);
      }
      if (Retcode != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(Retcode);
      }
      aGCBCOBPGMF_.WriteTo(output, _repeated_aGCBCOBPGMF_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      mEFNJKOFLND_.WriteTo(ref output, _repeated_mEFNJKOFLND_codec);
      if (KDIAFEMLEOE != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(KDIAFEMLEOE);
      }
      if (Retcode != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(Retcode);
      }
      aGCBCOBPGMF_.WriteTo(ref output, _repeated_aGCBCOBPGMF_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += mEFNJKOFLND_.CalculateSize(_repeated_mEFNJKOFLND_codec);
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (KDIAFEMLEOE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KDIAFEMLEOE);
      }
      size += aGCBCOBPGMF_.CalculateSize(_repeated_aGCBCOBPGMF_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetAetherDivideChallengeInfoScRsp other) {
      if (other == null) {
        return;
      }
      mEFNJKOFLND_.Add(other.mEFNJKOFLND_);
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.KDIAFEMLEOE != 0) {
        KDIAFEMLEOE = other.KDIAFEMLEOE;
      }
      aGCBCOBPGMF_.Add(other.aGCBCOBPGMF_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 42:
          case 40: {
            mEFNJKOFLND_.AddEntriesFrom(input, _repeated_mEFNJKOFLND_codec);
            break;
          }
          case 56: {
            KDIAFEMLEOE = input.ReadUInt32();
            break;
          }
          case 80: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 114:
          case 112: {
            aGCBCOBPGMF_.AddEntriesFrom(input, _repeated_aGCBCOBPGMF_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 42:
          case 40: {
            mEFNJKOFLND_.AddEntriesFrom(ref input, _repeated_mEFNJKOFLND_codec);
            break;
          }
          case 56: {
            KDIAFEMLEOE = input.ReadUInt32();
            break;
          }
          case 80: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 114:
          case 112: {
            aGCBCOBPGMF_.AddEntriesFrom(ref input, _repeated_aGCBCOBPGMF_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
