// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetBagScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from GetBagScRsp.proto</summary>
  public static partial class GetBagScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for GetBagScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetBagScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFHZXRCYWdTY1JzcC5wcm90bxoLUmVsaWMucHJvdG8aD01hdGVyaWFsMC5w",
            "cm90bxoRSkxFSEZCT0hOSUUucHJvdG8aDlBpbGVJdGVtLnByb3RvGg9FcXVp",
            "cG1lbnQucHJvdG8aDk1hdGVyaWFsLnByb3RvGhVXYWl0RGVsUmVzb3VyY2Uu",
            "cHJvdG8aFFR1cm5Gb29kU3dpdGNoLnByb3RvItEDCgtHZXRCYWdTY1JzcBIf",
            "CgtQSE5HTUVMSktCRRgJIAMoCzIKLk1hdGVyaWFsMBIeCgtJRkVOTURQQk5L",
            "RxgKIAMoCzIJLk1hdGVyaWFsEhMKC0FPSUlIQ0ZNRlBIGAMgAygNEjAKFndh",
            "aXRfZGVsX3Jlc291cmNlX2xpc3QYCCADKAsyEC5XYWl0RGVsUmVzb3VyY2US",
            "HgoLQkFGRUJIRE9CRkoYBiADKAsyCS5QaWxlSXRlbRITCgtGREJKTEdESENE",
            "TxgPIAMoDRIPCgdyZXRjb2RlGAcgASgNEiIKDmVxdWlwbWVudF9saXN0GA4g",
            "AygLMgouRXF1aXBtZW50EhoKCnJlbGljX2xpc3QYBCADKAsyBi5SZWxpYxIk",
            "CgtLTUpFRk1GQkxMSRgFIAMoDjIPLlR1cm5Gb29kU3dpdGNoEh8KC0ZDT0tG",
            "RkVBUE1JGA0gAygLMgouTWF0ZXJpYWwwEhMKC0dFTUNBQ0pMUElKGAsgAygN",
            "EiEKC0dOQUxBTkpQRUdPGAIgAygLMgwuSkxFSEZCT0hOSUUSEwoLQUVQTklE",
            "UE9OS0MYDCABKA0SIAoNbWF0ZXJpYWxfbGlzdBgBIAMoCzIJLk1hdGVyaWFs",
            "Qh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.RelicReflection.Descriptor, global::EggLink.DanhengServer.Proto.Material0Reflection.Descriptor, global::EggLink.DanhengServer.Proto.JLEHFBOHNIEReflection.Descriptor, global::EggLink.DanhengServer.Proto.PileItemReflection.Descriptor, global::EggLink.DanhengServer.Proto.EquipmentReflection.Descriptor, global::EggLink.DanhengServer.Proto.MaterialReflection.Descriptor, global::EggLink.DanhengServer.Proto.WaitDelResourceReflection.Descriptor, global::EggLink.DanhengServer.Proto.TurnFoodSwitchReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.GetBagScRsp), global::EggLink.DanhengServer.Proto.GetBagScRsp.Parser, new[]{ "PHNGMELJKBE", "IFENMDPBNKG", "AOIIHCFMFPH", "WaitDelResourceList", "BAFEBHDOBFJ", "FDBJLGDHCDO", "Retcode", "EquipmentList", "RelicList", "KMJEFMFBLLI", "FCOKFFEAPMI", "GEMCACJLPIJ", "GNALANJPEGO", "AEPNIDPONKC", "MaterialList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetBagScRsp : pb::IMessage<GetBagScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetBagScRsp> _parser = new pb::MessageParser<GetBagScRsp>(() => new GetBagScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetBagScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.GetBagScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetBagScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetBagScRsp(GetBagScRsp other) : this() {
      pHNGMELJKBE_ = other.pHNGMELJKBE_.Clone();
      iFENMDPBNKG_ = other.iFENMDPBNKG_.Clone();
      aOIIHCFMFPH_ = other.aOIIHCFMFPH_.Clone();
      waitDelResourceList_ = other.waitDelResourceList_.Clone();
      bAFEBHDOBFJ_ = other.bAFEBHDOBFJ_.Clone();
      fDBJLGDHCDO_ = other.fDBJLGDHCDO_.Clone();
      retcode_ = other.retcode_;
      equipmentList_ = other.equipmentList_.Clone();
      relicList_ = other.relicList_.Clone();
      kMJEFMFBLLI_ = other.kMJEFMFBLLI_.Clone();
      fCOKFFEAPMI_ = other.fCOKFFEAPMI_.Clone();
      gEMCACJLPIJ_ = other.gEMCACJLPIJ_.Clone();
      gNALANJPEGO_ = other.gNALANJPEGO_.Clone();
      aEPNIDPONKC_ = other.aEPNIDPONKC_;
      materialList_ = other.materialList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetBagScRsp Clone() {
      return new GetBagScRsp(this);
    }

    /// <summary>Field number for the "PHNGMELJKBE" field.</summary>
    public const int PHNGMELJKBEFieldNumber = 9;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Material0> _repeated_pHNGMELJKBE_codec
        = pb::FieldCodec.ForMessage(74, global::EggLink.DanhengServer.Proto.Material0.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0> pHNGMELJKBE_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0> PHNGMELJKBE {
      get { return pHNGMELJKBE_; }
    }

    /// <summary>Field number for the "IFENMDPBNKG" field.</summary>
    public const int IFENMDPBNKGFieldNumber = 10;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Material> _repeated_iFENMDPBNKG_codec
        = pb::FieldCodec.ForMessage(82, global::EggLink.DanhengServer.Proto.Material.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material> iFENMDPBNKG_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material> IFENMDPBNKG {
      get { return iFENMDPBNKG_; }
    }

    /// <summary>Field number for the "AOIIHCFMFPH" field.</summary>
    public const int AOIIHCFMFPHFieldNumber = 3;
    private static readonly pb::FieldCodec<uint> _repeated_aOIIHCFMFPH_codec
        = pb::FieldCodec.ForUInt32(26);
    private readonly pbc::RepeatedField<uint> aOIIHCFMFPH_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> AOIIHCFMFPH {
      get { return aOIIHCFMFPH_; }
    }

    /// <summary>Field number for the "wait_del_resource_list" field.</summary>
    public const int WaitDelResourceListFieldNumber = 8;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.WaitDelResource> _repeated_waitDelResourceList_codec
        = pb::FieldCodec.ForMessage(66, global::EggLink.DanhengServer.Proto.WaitDelResource.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.WaitDelResource> waitDelResourceList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.WaitDelResource>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.WaitDelResource> WaitDelResourceList {
      get { return waitDelResourceList_; }
    }

    /// <summary>Field number for the "BAFEBHDOBFJ" field.</summary>
    public const int BAFEBHDOBFJFieldNumber = 6;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.PileItem> _repeated_bAFEBHDOBFJ_codec
        = pb::FieldCodec.ForMessage(50, global::EggLink.DanhengServer.Proto.PileItem.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PileItem> bAFEBHDOBFJ_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PileItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PileItem> BAFEBHDOBFJ {
      get { return bAFEBHDOBFJ_; }
    }

    /// <summary>Field number for the "FDBJLGDHCDO" field.</summary>
    public const int FDBJLGDHCDOFieldNumber = 15;
    private static readonly pb::FieldCodec<uint> _repeated_fDBJLGDHCDO_codec
        = pb::FieldCodec.ForUInt32(122);
    private readonly pbc::RepeatedField<uint> fDBJLGDHCDO_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> FDBJLGDHCDO {
      get { return fDBJLGDHCDO_; }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 7;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "equipment_list" field.</summary>
    public const int EquipmentListFieldNumber = 14;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Equipment> _repeated_equipmentList_codec
        = pb::FieldCodec.ForMessage(114, global::EggLink.DanhengServer.Proto.Equipment.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Equipment> equipmentList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Equipment>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Equipment> EquipmentList {
      get { return equipmentList_; }
    }

    /// <summary>Field number for the "relic_list" field.</summary>
    public const int RelicListFieldNumber = 4;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Relic> _repeated_relicList_codec
        = pb::FieldCodec.ForMessage(34, global::EggLink.DanhengServer.Proto.Relic.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Relic> relicList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Relic>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Relic> RelicList {
      get { return relicList_; }
    }

    /// <summary>Field number for the "KMJEFMFBLLI" field.</summary>
    public const int KMJEFMFBLLIFieldNumber = 5;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.TurnFoodSwitch> _repeated_kMJEFMFBLLI_codec
        = pb::FieldCodec.ForEnum(42, x => (int) x, x => (global::EggLink.DanhengServer.Proto.TurnFoodSwitch) x);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.TurnFoodSwitch> kMJEFMFBLLI_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.TurnFoodSwitch>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.TurnFoodSwitch> KMJEFMFBLLI {
      get { return kMJEFMFBLLI_; }
    }

    /// <summary>Field number for the "FCOKFFEAPMI" field.</summary>
    public const int FCOKFFEAPMIFieldNumber = 13;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Material0> _repeated_fCOKFFEAPMI_codec
        = pb::FieldCodec.ForMessage(106, global::EggLink.DanhengServer.Proto.Material0.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0> fCOKFFEAPMI_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material0> FCOKFFEAPMI {
      get { return fCOKFFEAPMI_; }
    }

    /// <summary>Field number for the "GEMCACJLPIJ" field.</summary>
    public const int GEMCACJLPIJFieldNumber = 11;
    private static readonly pb::FieldCodec<uint> _repeated_gEMCACJLPIJ_codec
        = pb::FieldCodec.ForUInt32(90);
    private readonly pbc::RepeatedField<uint> gEMCACJLPIJ_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> GEMCACJLPIJ {
      get { return gEMCACJLPIJ_; }
    }

    /// <summary>Field number for the "GNALANJPEGO" field.</summary>
    public const int GNALANJPEGOFieldNumber = 2;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.JLEHFBOHNIE> _repeated_gNALANJPEGO_codec
        = pb::FieldCodec.ForMessage(18, global::EggLink.DanhengServer.Proto.JLEHFBOHNIE.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JLEHFBOHNIE> gNALANJPEGO_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JLEHFBOHNIE>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JLEHFBOHNIE> GNALANJPEGO {
      get { return gNALANJPEGO_; }
    }

    /// <summary>Field number for the "AEPNIDPONKC" field.</summary>
    public const int AEPNIDPONKCFieldNumber = 12;
    private uint aEPNIDPONKC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AEPNIDPONKC {
      get { return aEPNIDPONKC_; }
      set {
        aEPNIDPONKC_ = value;
      }
    }

    /// <summary>Field number for the "material_list" field.</summary>
    public const int MaterialListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.Material> _repeated_materialList_codec
        = pb::FieldCodec.ForMessage(10, global::EggLink.DanhengServer.Proto.Material.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material> materialList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.Material> MaterialList {
      get { return materialList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetBagScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetBagScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pHNGMELJKBE_.Equals(other.pHNGMELJKBE_)) return false;
      if(!iFENMDPBNKG_.Equals(other.iFENMDPBNKG_)) return false;
      if(!aOIIHCFMFPH_.Equals(other.aOIIHCFMFPH_)) return false;
      if(!waitDelResourceList_.Equals(other.waitDelResourceList_)) return false;
      if(!bAFEBHDOBFJ_.Equals(other.bAFEBHDOBFJ_)) return false;
      if(!fDBJLGDHCDO_.Equals(other.fDBJLGDHCDO_)) return false;
      if (Retcode != other.Retcode) return false;
      if(!equipmentList_.Equals(other.equipmentList_)) return false;
      if(!relicList_.Equals(other.relicList_)) return false;
      if(!kMJEFMFBLLI_.Equals(other.kMJEFMFBLLI_)) return false;
      if(!fCOKFFEAPMI_.Equals(other.fCOKFFEAPMI_)) return false;
      if(!gEMCACJLPIJ_.Equals(other.gEMCACJLPIJ_)) return false;
      if(!gNALANJPEGO_.Equals(other.gNALANJPEGO_)) return false;
      if (AEPNIDPONKC != other.AEPNIDPONKC) return false;
      if(!materialList_.Equals(other.materialList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pHNGMELJKBE_.GetHashCode();
      hash ^= iFENMDPBNKG_.GetHashCode();
      hash ^= aOIIHCFMFPH_.GetHashCode();
      hash ^= waitDelResourceList_.GetHashCode();
      hash ^= bAFEBHDOBFJ_.GetHashCode();
      hash ^= fDBJLGDHCDO_.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      hash ^= equipmentList_.GetHashCode();
      hash ^= relicList_.GetHashCode();
      hash ^= kMJEFMFBLLI_.GetHashCode();
      hash ^= fCOKFFEAPMI_.GetHashCode();
      hash ^= gEMCACJLPIJ_.GetHashCode();
      hash ^= gNALANJPEGO_.GetHashCode();
      if (AEPNIDPONKC != 0) hash ^= AEPNIDPONKC.GetHashCode();
      hash ^= materialList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      materialList_.WriteTo(output, _repeated_materialList_codec);
      gNALANJPEGO_.WriteTo(output, _repeated_gNALANJPEGO_codec);
      aOIIHCFMFPH_.WriteTo(output, _repeated_aOIIHCFMFPH_codec);
      relicList_.WriteTo(output, _repeated_relicList_codec);
      kMJEFMFBLLI_.WriteTo(output, _repeated_kMJEFMFBLLI_codec);
      bAFEBHDOBFJ_.WriteTo(output, _repeated_bAFEBHDOBFJ_codec);
      if (Retcode != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Retcode);
      }
      waitDelResourceList_.WriteTo(output, _repeated_waitDelResourceList_codec);
      pHNGMELJKBE_.WriteTo(output, _repeated_pHNGMELJKBE_codec);
      iFENMDPBNKG_.WriteTo(output, _repeated_iFENMDPBNKG_codec);
      gEMCACJLPIJ_.WriteTo(output, _repeated_gEMCACJLPIJ_codec);
      if (AEPNIDPONKC != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(AEPNIDPONKC);
      }
      fCOKFFEAPMI_.WriteTo(output, _repeated_fCOKFFEAPMI_codec);
      equipmentList_.WriteTo(output, _repeated_equipmentList_codec);
      fDBJLGDHCDO_.WriteTo(output, _repeated_fDBJLGDHCDO_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      materialList_.WriteTo(ref output, _repeated_materialList_codec);
      gNALANJPEGO_.WriteTo(ref output, _repeated_gNALANJPEGO_codec);
      aOIIHCFMFPH_.WriteTo(ref output, _repeated_aOIIHCFMFPH_codec);
      relicList_.WriteTo(ref output, _repeated_relicList_codec);
      kMJEFMFBLLI_.WriteTo(ref output, _repeated_kMJEFMFBLLI_codec);
      bAFEBHDOBFJ_.WriteTo(ref output, _repeated_bAFEBHDOBFJ_codec);
      if (Retcode != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Retcode);
      }
      waitDelResourceList_.WriteTo(ref output, _repeated_waitDelResourceList_codec);
      pHNGMELJKBE_.WriteTo(ref output, _repeated_pHNGMELJKBE_codec);
      iFENMDPBNKG_.WriteTo(ref output, _repeated_iFENMDPBNKG_codec);
      gEMCACJLPIJ_.WriteTo(ref output, _repeated_gEMCACJLPIJ_codec);
      if (AEPNIDPONKC != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(AEPNIDPONKC);
      }
      fCOKFFEAPMI_.WriteTo(ref output, _repeated_fCOKFFEAPMI_codec);
      equipmentList_.WriteTo(ref output, _repeated_equipmentList_codec);
      fDBJLGDHCDO_.WriteTo(ref output, _repeated_fDBJLGDHCDO_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += pHNGMELJKBE_.CalculateSize(_repeated_pHNGMELJKBE_codec);
      size += iFENMDPBNKG_.CalculateSize(_repeated_iFENMDPBNKG_codec);
      size += aOIIHCFMFPH_.CalculateSize(_repeated_aOIIHCFMFPH_codec);
      size += waitDelResourceList_.CalculateSize(_repeated_waitDelResourceList_codec);
      size += bAFEBHDOBFJ_.CalculateSize(_repeated_bAFEBHDOBFJ_codec);
      size += fDBJLGDHCDO_.CalculateSize(_repeated_fDBJLGDHCDO_codec);
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      size += equipmentList_.CalculateSize(_repeated_equipmentList_codec);
      size += relicList_.CalculateSize(_repeated_relicList_codec);
      size += kMJEFMFBLLI_.CalculateSize(_repeated_kMJEFMFBLLI_codec);
      size += fCOKFFEAPMI_.CalculateSize(_repeated_fCOKFFEAPMI_codec);
      size += gEMCACJLPIJ_.CalculateSize(_repeated_gEMCACJLPIJ_codec);
      size += gNALANJPEGO_.CalculateSize(_repeated_gNALANJPEGO_codec);
      if (AEPNIDPONKC != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AEPNIDPONKC);
      }
      size += materialList_.CalculateSize(_repeated_materialList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetBagScRsp other) {
      if (other == null) {
        return;
      }
      pHNGMELJKBE_.Add(other.pHNGMELJKBE_);
      iFENMDPBNKG_.Add(other.iFENMDPBNKG_);
      aOIIHCFMFPH_.Add(other.aOIIHCFMFPH_);
      waitDelResourceList_.Add(other.waitDelResourceList_);
      bAFEBHDOBFJ_.Add(other.bAFEBHDOBFJ_);
      fDBJLGDHCDO_.Add(other.fDBJLGDHCDO_);
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      equipmentList_.Add(other.equipmentList_);
      relicList_.Add(other.relicList_);
      kMJEFMFBLLI_.Add(other.kMJEFMFBLLI_);
      fCOKFFEAPMI_.Add(other.fCOKFFEAPMI_);
      gEMCACJLPIJ_.Add(other.gEMCACJLPIJ_);
      gNALANJPEGO_.Add(other.gNALANJPEGO_);
      if (other.AEPNIDPONKC != 0) {
        AEPNIDPONKC = other.AEPNIDPONKC;
      }
      materialList_.Add(other.materialList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            materialList_.AddEntriesFrom(input, _repeated_materialList_codec);
            break;
          }
          case 18: {
            gNALANJPEGO_.AddEntriesFrom(input, _repeated_gNALANJPEGO_codec);
            break;
          }
          case 26:
          case 24: {
            aOIIHCFMFPH_.AddEntriesFrom(input, _repeated_aOIIHCFMFPH_codec);
            break;
          }
          case 34: {
            relicList_.AddEntriesFrom(input, _repeated_relicList_codec);
            break;
          }
          case 42:
          case 40: {
            kMJEFMFBLLI_.AddEntriesFrom(input, _repeated_kMJEFMFBLLI_codec);
            break;
          }
          case 50: {
            bAFEBHDOBFJ_.AddEntriesFrom(input, _repeated_bAFEBHDOBFJ_codec);
            break;
          }
          case 56: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 66: {
            waitDelResourceList_.AddEntriesFrom(input, _repeated_waitDelResourceList_codec);
            break;
          }
          case 74: {
            pHNGMELJKBE_.AddEntriesFrom(input, _repeated_pHNGMELJKBE_codec);
            break;
          }
          case 82: {
            iFENMDPBNKG_.AddEntriesFrom(input, _repeated_iFENMDPBNKG_codec);
            break;
          }
          case 90:
          case 88: {
            gEMCACJLPIJ_.AddEntriesFrom(input, _repeated_gEMCACJLPIJ_codec);
            break;
          }
          case 96: {
            AEPNIDPONKC = input.ReadUInt32();
            break;
          }
          case 106: {
            fCOKFFEAPMI_.AddEntriesFrom(input, _repeated_fCOKFFEAPMI_codec);
            break;
          }
          case 114: {
            equipmentList_.AddEntriesFrom(input, _repeated_equipmentList_codec);
            break;
          }
          case 122:
          case 120: {
            fDBJLGDHCDO_.AddEntriesFrom(input, _repeated_fDBJLGDHCDO_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            materialList_.AddEntriesFrom(ref input, _repeated_materialList_codec);
            break;
          }
          case 18: {
            gNALANJPEGO_.AddEntriesFrom(ref input, _repeated_gNALANJPEGO_codec);
            break;
          }
          case 26:
          case 24: {
            aOIIHCFMFPH_.AddEntriesFrom(ref input, _repeated_aOIIHCFMFPH_codec);
            break;
          }
          case 34: {
            relicList_.AddEntriesFrom(ref input, _repeated_relicList_codec);
            break;
          }
          case 42:
          case 40: {
            kMJEFMFBLLI_.AddEntriesFrom(ref input, _repeated_kMJEFMFBLLI_codec);
            break;
          }
          case 50: {
            bAFEBHDOBFJ_.AddEntriesFrom(ref input, _repeated_bAFEBHDOBFJ_codec);
            break;
          }
          case 56: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 66: {
            waitDelResourceList_.AddEntriesFrom(ref input, _repeated_waitDelResourceList_codec);
            break;
          }
          case 74: {
            pHNGMELJKBE_.AddEntriesFrom(ref input, _repeated_pHNGMELJKBE_codec);
            break;
          }
          case 82: {
            iFENMDPBNKG_.AddEntriesFrom(ref input, _repeated_iFENMDPBNKG_codec);
            break;
          }
          case 90:
          case 88: {
            gEMCACJLPIJ_.AddEntriesFrom(ref input, _repeated_gEMCACJLPIJ_codec);
            break;
          }
          case 96: {
            AEPNIDPONKC = input.ReadUInt32();
            break;
          }
          case 106: {
            fCOKFFEAPMI_.AddEntriesFrom(ref input, _repeated_fCOKFFEAPMI_codec);
            break;
          }
          case 114: {
            equipmentList_.AddEntriesFrom(ref input, _repeated_equipmentList_codec);
            break;
          }
          case 122:
          case 120: {
            fDBJLGDHCDO_.AddEntriesFrom(ref input, _repeated_fDBJLGDHCDO_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
