// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetMuseumInfoScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from GetMuseumInfoScRsp.proto</summary>
  public static partial class GetMuseumInfoScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for GetMuseumInfoScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetMuseumInfoScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhHZXRNdXNldW1JbmZvU2NSc3AucHJvdG8aEUtPUEJNR0JLQUJFLnByb3Rv",
            "GhFMUE5BQVBHQ0lORi5wcm90bxoRSE1KR0VDS0NLTU0ucHJvdG8aEUhFS01K",
            "SUNHTk9LLnByb3RvIuACChJHZXRNdXNldW1JbmZvU2NSc3ASDwoHcmV0Y29k",
            "ZRgHIAEoDRIhCgtQSUJFRkVGR01OThgCIAEoCzIMLkxQTkFBUEdDSU5GEhMK",
            "C0JGS0JMS05CSEZCGAwgASgNEiEKC0VHRk1ITkNBS01MGAggAygLMgwuSEVL",
            "TUpJQ0dOT0sSEwoLRkxOT0dFTEZPRFAYCSABKA0SEwoLTEFEUE9HTEhOSkoY",
            "DSADKA0SEwoLTk1GTkRGTExPSU0YDiABKA0SIQoLSEhERkZFRE5MR00YCiAB",
            "KAsyDC5ITUpHRUNLQ0tNTRINCgVsZXZlbBgEIAEoDRITCgtOQkdQT1BPS0VM",
            "TxgPIAEoDRITCgtDUEtNSUFPTEdKSxgLIAMoDRIhCgtKT0ZOSk1QR05IQhgB",
            "IAMoCzIMLktPUEJNR0JLQUJFEhMKC0pQSUtLRkdKTUNFGAUgASgNEgsKA2V4",
            "cBgGIAEoDUIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.KOPBMGBKABEReflection.Descriptor, global::EggLink.DanhengServer.Proto.LPNAAPGCINFReflection.Descriptor, global::EggLink.DanhengServer.Proto.HMJGECKCKMMReflection.Descriptor, global::EggLink.DanhengServer.Proto.HEKMJICGNOKReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.GetMuseumInfoScRsp), global::EggLink.DanhengServer.Proto.GetMuseumInfoScRsp.Parser, new[]{ "Retcode", "PIBEFEFGMNN", "BFKBLKNBHFB", "EGFMHNCAKML", "FLNOGELFODP", "LADPOGLHNJJ", "NMFNDFLLOIM", "HHDFFEDNLGM", "Level", "NBGPOPOKELO", "CPKMIAOLGJK", "JOFNJMPGNHB", "JPIKKFGJMCE", "Exp" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetMuseumInfoScRsp : pb::IMessage<GetMuseumInfoScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetMuseumInfoScRsp> _parser = new pb::MessageParser<GetMuseumInfoScRsp>(() => new GetMuseumInfoScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetMuseumInfoScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.GetMuseumInfoScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetMuseumInfoScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetMuseumInfoScRsp(GetMuseumInfoScRsp other) : this() {
      retcode_ = other.retcode_;
      pIBEFEFGMNN_ = other.pIBEFEFGMNN_ != null ? other.pIBEFEFGMNN_.Clone() : null;
      bFKBLKNBHFB_ = other.bFKBLKNBHFB_;
      eGFMHNCAKML_ = other.eGFMHNCAKML_.Clone();
      fLNOGELFODP_ = other.fLNOGELFODP_;
      lADPOGLHNJJ_ = other.lADPOGLHNJJ_.Clone();
      nMFNDFLLOIM_ = other.nMFNDFLLOIM_;
      hHDFFEDNLGM_ = other.hHDFFEDNLGM_ != null ? other.hHDFFEDNLGM_.Clone() : null;
      level_ = other.level_;
      nBGPOPOKELO_ = other.nBGPOPOKELO_;
      cPKMIAOLGJK_ = other.cPKMIAOLGJK_.Clone();
      jOFNJMPGNHB_ = other.jOFNJMPGNHB_.Clone();
      jPIKKFGJMCE_ = other.jPIKKFGJMCE_;
      exp_ = other.exp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetMuseumInfoScRsp Clone() {
      return new GetMuseumInfoScRsp(this);
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 7;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "PIBEFEFGMNN" field.</summary>
    public const int PIBEFEFGMNNFieldNumber = 2;
    private global::EggLink.DanhengServer.Proto.LPNAAPGCINF pIBEFEFGMNN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.LPNAAPGCINF PIBEFEFGMNN {
      get { return pIBEFEFGMNN_; }
      set {
        pIBEFEFGMNN_ = value;
      }
    }

    /// <summary>Field number for the "BFKBLKNBHFB" field.</summary>
    public const int BFKBLKNBHFBFieldNumber = 12;
    private uint bFKBLKNBHFB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BFKBLKNBHFB {
      get { return bFKBLKNBHFB_; }
      set {
        bFKBLKNBHFB_ = value;
      }
    }

    /// <summary>Field number for the "EGFMHNCAKML" field.</summary>
    public const int EGFMHNCAKMLFieldNumber = 8;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.HEKMJICGNOK> _repeated_eGFMHNCAKML_codec
        = pb::FieldCodec.ForMessage(66, global::EggLink.DanhengServer.Proto.HEKMJICGNOK.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HEKMJICGNOK> eGFMHNCAKML_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HEKMJICGNOK>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HEKMJICGNOK> EGFMHNCAKML {
      get { return eGFMHNCAKML_; }
    }

    /// <summary>Field number for the "FLNOGELFODP" field.</summary>
    public const int FLNOGELFODPFieldNumber = 9;
    private uint fLNOGELFODP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FLNOGELFODP {
      get { return fLNOGELFODP_; }
      set {
        fLNOGELFODP_ = value;
      }
    }

    /// <summary>Field number for the "LADPOGLHNJJ" field.</summary>
    public const int LADPOGLHNJJFieldNumber = 13;
    private static readonly pb::FieldCodec<uint> _repeated_lADPOGLHNJJ_codec
        = pb::FieldCodec.ForUInt32(106);
    private readonly pbc::RepeatedField<uint> lADPOGLHNJJ_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> LADPOGLHNJJ {
      get { return lADPOGLHNJJ_; }
    }

    /// <summary>Field number for the "NMFNDFLLOIM" field.</summary>
    public const int NMFNDFLLOIMFieldNumber = 14;
    private uint nMFNDFLLOIM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NMFNDFLLOIM {
      get { return nMFNDFLLOIM_; }
      set {
        nMFNDFLLOIM_ = value;
      }
    }

    /// <summary>Field number for the "HHDFFEDNLGM" field.</summary>
    public const int HHDFFEDNLGMFieldNumber = 10;
    private global::EggLink.DanhengServer.Proto.HMJGECKCKMM hHDFFEDNLGM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.HMJGECKCKMM HHDFFEDNLGM {
      get { return hHDFFEDNLGM_; }
      set {
        hHDFFEDNLGM_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 4;
    private uint level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "NBGPOPOKELO" field.</summary>
    public const int NBGPOPOKELOFieldNumber = 15;
    private uint nBGPOPOKELO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NBGPOPOKELO {
      get { return nBGPOPOKELO_; }
      set {
        nBGPOPOKELO_ = value;
      }
    }

    /// <summary>Field number for the "CPKMIAOLGJK" field.</summary>
    public const int CPKMIAOLGJKFieldNumber = 11;
    private static readonly pb::FieldCodec<uint> _repeated_cPKMIAOLGJK_codec
        = pb::FieldCodec.ForUInt32(90);
    private readonly pbc::RepeatedField<uint> cPKMIAOLGJK_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> CPKMIAOLGJK {
      get { return cPKMIAOLGJK_; }
    }

    /// <summary>Field number for the "JOFNJMPGNHB" field.</summary>
    public const int JOFNJMPGNHBFieldNumber = 1;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.KOPBMGBKABE> _repeated_jOFNJMPGNHB_codec
        = pb::FieldCodec.ForMessage(10, global::EggLink.DanhengServer.Proto.KOPBMGBKABE.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.KOPBMGBKABE> jOFNJMPGNHB_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.KOPBMGBKABE>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.KOPBMGBKABE> JOFNJMPGNHB {
      get { return jOFNJMPGNHB_; }
    }

    /// <summary>Field number for the "JPIKKFGJMCE" field.</summary>
    public const int JPIKKFGJMCEFieldNumber = 5;
    private uint jPIKKFGJMCE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint JPIKKFGJMCE {
      get { return jPIKKFGJMCE_; }
      set {
        jPIKKFGJMCE_ = value;
      }
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 6;
    private uint exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetMuseumInfoScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetMuseumInfoScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Retcode != other.Retcode) return false;
      if (!object.Equals(PIBEFEFGMNN, other.PIBEFEFGMNN)) return false;
      if (BFKBLKNBHFB != other.BFKBLKNBHFB) return false;
      if(!eGFMHNCAKML_.Equals(other.eGFMHNCAKML_)) return false;
      if (FLNOGELFODP != other.FLNOGELFODP) return false;
      if(!lADPOGLHNJJ_.Equals(other.lADPOGLHNJJ_)) return false;
      if (NMFNDFLLOIM != other.NMFNDFLLOIM) return false;
      if (!object.Equals(HHDFFEDNLGM, other.HHDFFEDNLGM)) return false;
      if (Level != other.Level) return false;
      if (NBGPOPOKELO != other.NBGPOPOKELO) return false;
      if(!cPKMIAOLGJK_.Equals(other.cPKMIAOLGJK_)) return false;
      if(!jOFNJMPGNHB_.Equals(other.jOFNJMPGNHB_)) return false;
      if (JPIKKFGJMCE != other.JPIKKFGJMCE) return false;
      if (Exp != other.Exp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (pIBEFEFGMNN_ != null) hash ^= PIBEFEFGMNN.GetHashCode();
      if (BFKBLKNBHFB != 0) hash ^= BFKBLKNBHFB.GetHashCode();
      hash ^= eGFMHNCAKML_.GetHashCode();
      if (FLNOGELFODP != 0) hash ^= FLNOGELFODP.GetHashCode();
      hash ^= lADPOGLHNJJ_.GetHashCode();
      if (NMFNDFLLOIM != 0) hash ^= NMFNDFLLOIM.GetHashCode();
      if (hHDFFEDNLGM_ != null) hash ^= HHDFFEDNLGM.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (NBGPOPOKELO != 0) hash ^= NBGPOPOKELO.GetHashCode();
      hash ^= cPKMIAOLGJK_.GetHashCode();
      hash ^= jOFNJMPGNHB_.GetHashCode();
      if (JPIKKFGJMCE != 0) hash ^= JPIKKFGJMCE.GetHashCode();
      if (Exp != 0) hash ^= Exp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      jOFNJMPGNHB_.WriteTo(output, _repeated_jOFNJMPGNHB_codec);
      if (pIBEFEFGMNN_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PIBEFEFGMNN);
      }
      if (Level != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Level);
      }
      if (JPIKKFGJMCE != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(JPIKKFGJMCE);
      }
      if (Exp != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Exp);
      }
      if (Retcode != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Retcode);
      }
      eGFMHNCAKML_.WriteTo(output, _repeated_eGFMHNCAKML_codec);
      if (FLNOGELFODP != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(FLNOGELFODP);
      }
      if (hHDFFEDNLGM_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(HHDFFEDNLGM);
      }
      cPKMIAOLGJK_.WriteTo(output, _repeated_cPKMIAOLGJK_codec);
      if (BFKBLKNBHFB != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(BFKBLKNBHFB);
      }
      lADPOGLHNJJ_.WriteTo(output, _repeated_lADPOGLHNJJ_codec);
      if (NMFNDFLLOIM != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(NMFNDFLLOIM);
      }
      if (NBGPOPOKELO != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(NBGPOPOKELO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      jOFNJMPGNHB_.WriteTo(ref output, _repeated_jOFNJMPGNHB_codec);
      if (pIBEFEFGMNN_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PIBEFEFGMNN);
      }
      if (Level != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Level);
      }
      if (JPIKKFGJMCE != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(JPIKKFGJMCE);
      }
      if (Exp != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Exp);
      }
      if (Retcode != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Retcode);
      }
      eGFMHNCAKML_.WriteTo(ref output, _repeated_eGFMHNCAKML_codec);
      if (FLNOGELFODP != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(FLNOGELFODP);
      }
      if (hHDFFEDNLGM_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(HHDFFEDNLGM);
      }
      cPKMIAOLGJK_.WriteTo(ref output, _repeated_cPKMIAOLGJK_codec);
      if (BFKBLKNBHFB != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(BFKBLKNBHFB);
      }
      lADPOGLHNJJ_.WriteTo(ref output, _repeated_lADPOGLHNJJ_codec);
      if (NMFNDFLLOIM != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(NMFNDFLLOIM);
      }
      if (NBGPOPOKELO != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(NBGPOPOKELO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (pIBEFEFGMNN_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PIBEFEFGMNN);
      }
      if (BFKBLKNBHFB != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BFKBLKNBHFB);
      }
      size += eGFMHNCAKML_.CalculateSize(_repeated_eGFMHNCAKML_codec);
      if (FLNOGELFODP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FLNOGELFODP);
      }
      size += lADPOGLHNJJ_.CalculateSize(_repeated_lADPOGLHNJJ_codec);
      if (NMFNDFLLOIM != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NMFNDFLLOIM);
      }
      if (hHDFFEDNLGM_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HHDFFEDNLGM);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Level);
      }
      if (NBGPOPOKELO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NBGPOPOKELO);
      }
      size += cPKMIAOLGJK_.CalculateSize(_repeated_cPKMIAOLGJK_codec);
      size += jOFNJMPGNHB_.CalculateSize(_repeated_jOFNJMPGNHB_codec);
      if (JPIKKFGJMCE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JPIKKFGJMCE);
      }
      if (Exp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Exp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetMuseumInfoScRsp other) {
      if (other == null) {
        return;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.pIBEFEFGMNN_ != null) {
        if (pIBEFEFGMNN_ == null) {
          PIBEFEFGMNN = new global::EggLink.DanhengServer.Proto.LPNAAPGCINF();
        }
        PIBEFEFGMNN.MergeFrom(other.PIBEFEFGMNN);
      }
      if (other.BFKBLKNBHFB != 0) {
        BFKBLKNBHFB = other.BFKBLKNBHFB;
      }
      eGFMHNCAKML_.Add(other.eGFMHNCAKML_);
      if (other.FLNOGELFODP != 0) {
        FLNOGELFODP = other.FLNOGELFODP;
      }
      lADPOGLHNJJ_.Add(other.lADPOGLHNJJ_);
      if (other.NMFNDFLLOIM != 0) {
        NMFNDFLLOIM = other.NMFNDFLLOIM;
      }
      if (other.hHDFFEDNLGM_ != null) {
        if (hHDFFEDNLGM_ == null) {
          HHDFFEDNLGM = new global::EggLink.DanhengServer.Proto.HMJGECKCKMM();
        }
        HHDFFEDNLGM.MergeFrom(other.HHDFFEDNLGM);
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.NBGPOPOKELO != 0) {
        NBGPOPOKELO = other.NBGPOPOKELO;
      }
      cPKMIAOLGJK_.Add(other.cPKMIAOLGJK_);
      jOFNJMPGNHB_.Add(other.jOFNJMPGNHB_);
      if (other.JPIKKFGJMCE != 0) {
        JPIKKFGJMCE = other.JPIKKFGJMCE;
      }
      if (other.Exp != 0) {
        Exp = other.Exp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            jOFNJMPGNHB_.AddEntriesFrom(input, _repeated_jOFNJMPGNHB_codec);
            break;
          }
          case 18: {
            if (pIBEFEFGMNN_ == null) {
              PIBEFEFGMNN = new global::EggLink.DanhengServer.Proto.LPNAAPGCINF();
            }
            input.ReadMessage(PIBEFEFGMNN);
            break;
          }
          case 32: {
            Level = input.ReadUInt32();
            break;
          }
          case 40: {
            JPIKKFGJMCE = input.ReadUInt32();
            break;
          }
          case 48: {
            Exp = input.ReadUInt32();
            break;
          }
          case 56: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 66: {
            eGFMHNCAKML_.AddEntriesFrom(input, _repeated_eGFMHNCAKML_codec);
            break;
          }
          case 72: {
            FLNOGELFODP = input.ReadUInt32();
            break;
          }
          case 82: {
            if (hHDFFEDNLGM_ == null) {
              HHDFFEDNLGM = new global::EggLink.DanhengServer.Proto.HMJGECKCKMM();
            }
            input.ReadMessage(HHDFFEDNLGM);
            break;
          }
          case 90:
          case 88: {
            cPKMIAOLGJK_.AddEntriesFrom(input, _repeated_cPKMIAOLGJK_codec);
            break;
          }
          case 96: {
            BFKBLKNBHFB = input.ReadUInt32();
            break;
          }
          case 106:
          case 104: {
            lADPOGLHNJJ_.AddEntriesFrom(input, _repeated_lADPOGLHNJJ_codec);
            break;
          }
          case 112: {
            NMFNDFLLOIM = input.ReadUInt32();
            break;
          }
          case 120: {
            NBGPOPOKELO = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            jOFNJMPGNHB_.AddEntriesFrom(ref input, _repeated_jOFNJMPGNHB_codec);
            break;
          }
          case 18: {
            if (pIBEFEFGMNN_ == null) {
              PIBEFEFGMNN = new global::EggLink.DanhengServer.Proto.LPNAAPGCINF();
            }
            input.ReadMessage(PIBEFEFGMNN);
            break;
          }
          case 32: {
            Level = input.ReadUInt32();
            break;
          }
          case 40: {
            JPIKKFGJMCE = input.ReadUInt32();
            break;
          }
          case 48: {
            Exp = input.ReadUInt32();
            break;
          }
          case 56: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 66: {
            eGFMHNCAKML_.AddEntriesFrom(ref input, _repeated_eGFMHNCAKML_codec);
            break;
          }
          case 72: {
            FLNOGELFODP = input.ReadUInt32();
            break;
          }
          case 82: {
            if (hHDFFEDNLGM_ == null) {
              HHDFFEDNLGM = new global::EggLink.DanhengServer.Proto.HMJGECKCKMM();
            }
            input.ReadMessage(HHDFFEDNLGM);
            break;
          }
          case 90:
          case 88: {
            cPKMIAOLGJK_.AddEntriesFrom(ref input, _repeated_cPKMIAOLGJK_codec);
            break;
          }
          case 96: {
            BFKBLKNBHFB = input.ReadUInt32();
            break;
          }
          case 106:
          case 104: {
            lADPOGLHNJJ_.AddEntriesFrom(ref input, _repeated_lADPOGLHNJJ_codec);
            break;
          }
          case 112: {
            NMFNDFLLOIM = input.ReadUInt32();
            break;
          }
          case 120: {
            NBGPOPOKELO = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
