// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetRogueShopBuffInfoScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from GetRogueShopBuffInfoScRsp.proto</summary>
  public static partial class GetRogueShopBuffInfoScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for GetRogueShopBuffInfoScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetRogueShopBuffInfoScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9HZXRSb2d1ZVNob3BCdWZmSW5mb1NjUnNwLnByb3RvGhJJdGVtQ29zdERh",
            "dGEucHJvdG8aEUpGS0xJRUhLRERFLnByb3RvIowBChlHZXRSb2d1ZVNob3BC",
            "dWZmSW5mb1NjUnNwEhMKC05HT0dGRURMTE9PGAggASgIEiIKC0JETkxHRUFO",
            "R0FPGAMgASgLMg0uSXRlbUNvc3REYXRhEiUKD3JvZ3VlX2J1ZmZfaW5mbxgC",
            "IAEoCzIMLkpGS0xJRUhLRERFEg8KB3JldGNvZGUYDiABKA1CHqoCG0VnZ0xp",
            "bmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.ItemCostDataReflection.Descriptor, global::EggLink.DanhengServer.Proto.JFKLIEHKDDEReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.GetRogueShopBuffInfoScRsp), global::EggLink.DanhengServer.Proto.GetRogueShopBuffInfoScRsp.Parser, new[]{ "NGOGFEDLLOO", "BDNLGEANGAO", "RogueBuffInfo", "Retcode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetRogueShopBuffInfoScRsp : pb::IMessage<GetRogueShopBuffInfoScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetRogueShopBuffInfoScRsp> _parser = new pb::MessageParser<GetRogueShopBuffInfoScRsp>(() => new GetRogueShopBuffInfoScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetRogueShopBuffInfoScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.GetRogueShopBuffInfoScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRogueShopBuffInfoScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRogueShopBuffInfoScRsp(GetRogueShopBuffInfoScRsp other) : this() {
      nGOGFEDLLOO_ = other.nGOGFEDLLOO_;
      bDNLGEANGAO_ = other.bDNLGEANGAO_ != null ? other.bDNLGEANGAO_.Clone() : null;
      rogueBuffInfo_ = other.rogueBuffInfo_ != null ? other.rogueBuffInfo_.Clone() : null;
      retcode_ = other.retcode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetRogueShopBuffInfoScRsp Clone() {
      return new GetRogueShopBuffInfoScRsp(this);
    }

    /// <summary>Field number for the "NGOGFEDLLOO" field.</summary>
    public const int NGOGFEDLLOOFieldNumber = 8;
    private bool nGOGFEDLLOO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NGOGFEDLLOO {
      get { return nGOGFEDLLOO_; }
      set {
        nGOGFEDLLOO_ = value;
      }
    }

    /// <summary>Field number for the "BDNLGEANGAO" field.</summary>
    public const int BDNLGEANGAOFieldNumber = 3;
    private global::EggLink.DanhengServer.Proto.ItemCostData bDNLGEANGAO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ItemCostData BDNLGEANGAO {
      get { return bDNLGEANGAO_; }
      set {
        bDNLGEANGAO_ = value;
      }
    }

    /// <summary>Field number for the "rogue_buff_info" field.</summary>
    public const int RogueBuffInfoFieldNumber = 2;
    private global::EggLink.DanhengServer.Proto.JFKLIEHKDDE rogueBuffInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.JFKLIEHKDDE RogueBuffInfo {
      get { return rogueBuffInfo_; }
      set {
        rogueBuffInfo_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 14;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetRogueShopBuffInfoScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetRogueShopBuffInfoScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NGOGFEDLLOO != other.NGOGFEDLLOO) return false;
      if (!object.Equals(BDNLGEANGAO, other.BDNLGEANGAO)) return false;
      if (!object.Equals(RogueBuffInfo, other.RogueBuffInfo)) return false;
      if (Retcode != other.Retcode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NGOGFEDLLOO != false) hash ^= NGOGFEDLLOO.GetHashCode();
      if (bDNLGEANGAO_ != null) hash ^= BDNLGEANGAO.GetHashCode();
      if (rogueBuffInfo_ != null) hash ^= RogueBuffInfo.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (rogueBuffInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RogueBuffInfo);
      }
      if (bDNLGEANGAO_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(BDNLGEANGAO);
      }
      if (NGOGFEDLLOO != false) {
        output.WriteRawTag(64);
        output.WriteBool(NGOGFEDLLOO);
      }
      if (Retcode != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (rogueBuffInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RogueBuffInfo);
      }
      if (bDNLGEANGAO_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(BDNLGEANGAO);
      }
      if (NGOGFEDLLOO != false) {
        output.WriteRawTag(64);
        output.WriteBool(NGOGFEDLLOO);
      }
      if (Retcode != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NGOGFEDLLOO != false) {
        size += 1 + 1;
      }
      if (bDNLGEANGAO_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BDNLGEANGAO);
      }
      if (rogueBuffInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RogueBuffInfo);
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetRogueShopBuffInfoScRsp other) {
      if (other == null) {
        return;
      }
      if (other.NGOGFEDLLOO != false) {
        NGOGFEDLLOO = other.NGOGFEDLLOO;
      }
      if (other.bDNLGEANGAO_ != null) {
        if (bDNLGEANGAO_ == null) {
          BDNLGEANGAO = new global::EggLink.DanhengServer.Proto.ItemCostData();
        }
        BDNLGEANGAO.MergeFrom(other.BDNLGEANGAO);
      }
      if (other.rogueBuffInfo_ != null) {
        if (rogueBuffInfo_ == null) {
          RogueBuffInfo = new global::EggLink.DanhengServer.Proto.JFKLIEHKDDE();
        }
        RogueBuffInfo.MergeFrom(other.RogueBuffInfo);
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (rogueBuffInfo_ == null) {
              RogueBuffInfo = new global::EggLink.DanhengServer.Proto.JFKLIEHKDDE();
            }
            input.ReadMessage(RogueBuffInfo);
            break;
          }
          case 26: {
            if (bDNLGEANGAO_ == null) {
              BDNLGEANGAO = new global::EggLink.DanhengServer.Proto.ItemCostData();
            }
            input.ReadMessage(BDNLGEANGAO);
            break;
          }
          case 64: {
            NGOGFEDLLOO = input.ReadBool();
            break;
          }
          case 112: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            if (rogueBuffInfo_ == null) {
              RogueBuffInfo = new global::EggLink.DanhengServer.Proto.JFKLIEHKDDE();
            }
            input.ReadMessage(RogueBuffInfo);
            break;
          }
          case 26: {
            if (bDNLGEANGAO_ == null) {
              BDNLGEANGAO = new global::EggLink.DanhengServer.Proto.ItemCostData();
            }
            input.ReadMessage(BDNLGEANGAO);
            break;
          }
          case 64: {
            NGOGFEDLLOO = input.ReadBool();
            break;
          }
          case 112: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
