// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HKFBMLKMOMJ.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from HKFBMLKMOMJ.proto</summary>
  public static partial class HKFBMLKMOMJReflection {

    #region Descriptor
    /// <summary>File descriptor for HKFBMLKMOMJ.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HKFBMLKMOMJReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFIS0ZCTUxLTU9NSi5wcm90bxoRTU1MQklCUEhCUEwucHJvdG8i7gEKC0hL",
            "RkJNTEtNT01KEhMKC0dER0hGS01ESUJCGAYgASgNEhMKC0FGSkVETEhNT0hB",
            "GAEgASgIEhMKC0ZJR0JISk9GQk5FGAUgASgNEhMKC0lOSklFRkZORUxOGAsg",
            "ASgNEhMKC2F2YXRhcl9saXN0GAkgAygNEiEKC0dQUEhKR0dGTUNCGAMgAygL",
            "MgwuTU1MQklCUEhCUEwSEwoLQk5QT09PRUpCTUEYDyABKA0SEwoLQ0lITk1F",
            "Q0lGTkkYDCABKA0SEwoLRkNNSUxKQk9ITFAYDSADKA0SFAoMY2hhbGxlbmdl",
            "X2lkGAogASgNQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.MMLBIBPHBPLReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.HKFBMLKMOMJ), global::EggLink.DanhengServer.Proto.HKFBMLKMOMJ.Parser, new[]{ "GDGHFKMDIBB", "AFJEDLHMOHA", "FIGBHJOFBNE", "INJIEFFNELN", "AvatarList", "GPPHJGGFMCB", "BNPOOOEJBMA", "CIHNMECIFNI", "FCMILJBOHLP", "ChallengeId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HKFBMLKMOMJ : pb::IMessage<HKFBMLKMOMJ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HKFBMLKMOMJ> _parser = new pb::MessageParser<HKFBMLKMOMJ>(() => new HKFBMLKMOMJ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HKFBMLKMOMJ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.HKFBMLKMOMJReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HKFBMLKMOMJ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HKFBMLKMOMJ(HKFBMLKMOMJ other) : this() {
      gDGHFKMDIBB_ = other.gDGHFKMDIBB_;
      aFJEDLHMOHA_ = other.aFJEDLHMOHA_;
      fIGBHJOFBNE_ = other.fIGBHJOFBNE_;
      iNJIEFFNELN_ = other.iNJIEFFNELN_;
      avatarList_ = other.avatarList_.Clone();
      gPPHJGGFMCB_ = other.gPPHJGGFMCB_.Clone();
      bNPOOOEJBMA_ = other.bNPOOOEJBMA_;
      cIHNMECIFNI_ = other.cIHNMECIFNI_;
      fCMILJBOHLP_ = other.fCMILJBOHLP_.Clone();
      challengeId_ = other.challengeId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HKFBMLKMOMJ Clone() {
      return new HKFBMLKMOMJ(this);
    }

    /// <summary>Field number for the "GDGHFKMDIBB" field.</summary>
    public const int GDGHFKMDIBBFieldNumber = 6;
    private uint gDGHFKMDIBB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GDGHFKMDIBB {
      get { return gDGHFKMDIBB_; }
      set {
        gDGHFKMDIBB_ = value;
      }
    }

    /// <summary>Field number for the "AFJEDLHMOHA" field.</summary>
    public const int AFJEDLHMOHAFieldNumber = 1;
    private bool aFJEDLHMOHA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AFJEDLHMOHA {
      get { return aFJEDLHMOHA_; }
      set {
        aFJEDLHMOHA_ = value;
      }
    }

    /// <summary>Field number for the "FIGBHJOFBNE" field.</summary>
    public const int FIGBHJOFBNEFieldNumber = 5;
    private uint fIGBHJOFBNE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FIGBHJOFBNE {
      get { return fIGBHJOFBNE_; }
      set {
        fIGBHJOFBNE_ = value;
      }
    }

    /// <summary>Field number for the "INJIEFFNELN" field.</summary>
    public const int INJIEFFNELNFieldNumber = 11;
    private uint iNJIEFFNELN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint INJIEFFNELN {
      get { return iNJIEFFNELN_; }
      set {
        iNJIEFFNELN_ = value;
      }
    }

    /// <summary>Field number for the "avatar_list" field.</summary>
    public const int AvatarListFieldNumber = 9;
    private static readonly pb::FieldCodec<uint> _repeated_avatarList_codec
        = pb::FieldCodec.ForUInt32(74);
    private readonly pbc::RepeatedField<uint> avatarList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> AvatarList {
      get { return avatarList_; }
    }

    /// <summary>Field number for the "GPPHJGGFMCB" field.</summary>
    public const int GPPHJGGFMCBFieldNumber = 3;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.MMLBIBPHBPL> _repeated_gPPHJGGFMCB_codec
        = pb::FieldCodec.ForMessage(26, global::EggLink.DanhengServer.Proto.MMLBIBPHBPL.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.MMLBIBPHBPL> gPPHJGGFMCB_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.MMLBIBPHBPL>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.MMLBIBPHBPL> GPPHJGGFMCB {
      get { return gPPHJGGFMCB_; }
    }

    /// <summary>Field number for the "BNPOOOEJBMA" field.</summary>
    public const int BNPOOOEJBMAFieldNumber = 15;
    private uint bNPOOOEJBMA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BNPOOOEJBMA {
      get { return bNPOOOEJBMA_; }
      set {
        bNPOOOEJBMA_ = value;
      }
    }

    /// <summary>Field number for the "CIHNMECIFNI" field.</summary>
    public const int CIHNMECIFNIFieldNumber = 12;
    private uint cIHNMECIFNI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CIHNMECIFNI {
      get { return cIHNMECIFNI_; }
      set {
        cIHNMECIFNI_ = value;
      }
    }

    /// <summary>Field number for the "FCMILJBOHLP" field.</summary>
    public const int FCMILJBOHLPFieldNumber = 13;
    private static readonly pb::FieldCodec<uint> _repeated_fCMILJBOHLP_codec
        = pb::FieldCodec.ForUInt32(106);
    private readonly pbc::RepeatedField<uint> fCMILJBOHLP_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> FCMILJBOHLP {
      get { return fCMILJBOHLP_; }
    }

    /// <summary>Field number for the "challenge_id" field.</summary>
    public const int ChallengeIdFieldNumber = 10;
    private uint challengeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ChallengeId {
      get { return challengeId_; }
      set {
        challengeId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HKFBMLKMOMJ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HKFBMLKMOMJ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GDGHFKMDIBB != other.GDGHFKMDIBB) return false;
      if (AFJEDLHMOHA != other.AFJEDLHMOHA) return false;
      if (FIGBHJOFBNE != other.FIGBHJOFBNE) return false;
      if (INJIEFFNELN != other.INJIEFFNELN) return false;
      if(!avatarList_.Equals(other.avatarList_)) return false;
      if(!gPPHJGGFMCB_.Equals(other.gPPHJGGFMCB_)) return false;
      if (BNPOOOEJBMA != other.BNPOOOEJBMA) return false;
      if (CIHNMECIFNI != other.CIHNMECIFNI) return false;
      if(!fCMILJBOHLP_.Equals(other.fCMILJBOHLP_)) return false;
      if (ChallengeId != other.ChallengeId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GDGHFKMDIBB != 0) hash ^= GDGHFKMDIBB.GetHashCode();
      if (AFJEDLHMOHA != false) hash ^= AFJEDLHMOHA.GetHashCode();
      if (FIGBHJOFBNE != 0) hash ^= FIGBHJOFBNE.GetHashCode();
      if (INJIEFFNELN != 0) hash ^= INJIEFFNELN.GetHashCode();
      hash ^= avatarList_.GetHashCode();
      hash ^= gPPHJGGFMCB_.GetHashCode();
      if (BNPOOOEJBMA != 0) hash ^= BNPOOOEJBMA.GetHashCode();
      if (CIHNMECIFNI != 0) hash ^= CIHNMECIFNI.GetHashCode();
      hash ^= fCMILJBOHLP_.GetHashCode();
      if (ChallengeId != 0) hash ^= ChallengeId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AFJEDLHMOHA != false) {
        output.WriteRawTag(8);
        output.WriteBool(AFJEDLHMOHA);
      }
      gPPHJGGFMCB_.WriteTo(output, _repeated_gPPHJGGFMCB_codec);
      if (FIGBHJOFBNE != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(FIGBHJOFBNE);
      }
      if (GDGHFKMDIBB != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(GDGHFKMDIBB);
      }
      avatarList_.WriteTo(output, _repeated_avatarList_codec);
      if (ChallengeId != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(ChallengeId);
      }
      if (INJIEFFNELN != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(INJIEFFNELN);
      }
      if (CIHNMECIFNI != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(CIHNMECIFNI);
      }
      fCMILJBOHLP_.WriteTo(output, _repeated_fCMILJBOHLP_codec);
      if (BNPOOOEJBMA != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(BNPOOOEJBMA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AFJEDLHMOHA != false) {
        output.WriteRawTag(8);
        output.WriteBool(AFJEDLHMOHA);
      }
      gPPHJGGFMCB_.WriteTo(ref output, _repeated_gPPHJGGFMCB_codec);
      if (FIGBHJOFBNE != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(FIGBHJOFBNE);
      }
      if (GDGHFKMDIBB != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(GDGHFKMDIBB);
      }
      avatarList_.WriteTo(ref output, _repeated_avatarList_codec);
      if (ChallengeId != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(ChallengeId);
      }
      if (INJIEFFNELN != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(INJIEFFNELN);
      }
      if (CIHNMECIFNI != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(CIHNMECIFNI);
      }
      fCMILJBOHLP_.WriteTo(ref output, _repeated_fCMILJBOHLP_codec);
      if (BNPOOOEJBMA != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(BNPOOOEJBMA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GDGHFKMDIBB != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GDGHFKMDIBB);
      }
      if (AFJEDLHMOHA != false) {
        size += 1 + 1;
      }
      if (FIGBHJOFBNE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FIGBHJOFBNE);
      }
      if (INJIEFFNELN != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(INJIEFFNELN);
      }
      size += avatarList_.CalculateSize(_repeated_avatarList_codec);
      size += gPPHJGGFMCB_.CalculateSize(_repeated_gPPHJGGFMCB_codec);
      if (BNPOOOEJBMA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BNPOOOEJBMA);
      }
      if (CIHNMECIFNI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CIHNMECIFNI);
      }
      size += fCMILJBOHLP_.CalculateSize(_repeated_fCMILJBOHLP_codec);
      if (ChallengeId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChallengeId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HKFBMLKMOMJ other) {
      if (other == null) {
        return;
      }
      if (other.GDGHFKMDIBB != 0) {
        GDGHFKMDIBB = other.GDGHFKMDIBB;
      }
      if (other.AFJEDLHMOHA != false) {
        AFJEDLHMOHA = other.AFJEDLHMOHA;
      }
      if (other.FIGBHJOFBNE != 0) {
        FIGBHJOFBNE = other.FIGBHJOFBNE;
      }
      if (other.INJIEFFNELN != 0) {
        INJIEFFNELN = other.INJIEFFNELN;
      }
      avatarList_.Add(other.avatarList_);
      gPPHJGGFMCB_.Add(other.gPPHJGGFMCB_);
      if (other.BNPOOOEJBMA != 0) {
        BNPOOOEJBMA = other.BNPOOOEJBMA;
      }
      if (other.CIHNMECIFNI != 0) {
        CIHNMECIFNI = other.CIHNMECIFNI;
      }
      fCMILJBOHLP_.Add(other.fCMILJBOHLP_);
      if (other.ChallengeId != 0) {
        ChallengeId = other.ChallengeId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AFJEDLHMOHA = input.ReadBool();
            break;
          }
          case 26: {
            gPPHJGGFMCB_.AddEntriesFrom(input, _repeated_gPPHJGGFMCB_codec);
            break;
          }
          case 40: {
            FIGBHJOFBNE = input.ReadUInt32();
            break;
          }
          case 48: {
            GDGHFKMDIBB = input.ReadUInt32();
            break;
          }
          case 74:
          case 72: {
            avatarList_.AddEntriesFrom(input, _repeated_avatarList_codec);
            break;
          }
          case 80: {
            ChallengeId = input.ReadUInt32();
            break;
          }
          case 88: {
            INJIEFFNELN = input.ReadUInt32();
            break;
          }
          case 96: {
            CIHNMECIFNI = input.ReadUInt32();
            break;
          }
          case 106:
          case 104: {
            fCMILJBOHLP_.AddEntriesFrom(input, _repeated_fCMILJBOHLP_codec);
            break;
          }
          case 120: {
            BNPOOOEJBMA = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AFJEDLHMOHA = input.ReadBool();
            break;
          }
          case 26: {
            gPPHJGGFMCB_.AddEntriesFrom(ref input, _repeated_gPPHJGGFMCB_codec);
            break;
          }
          case 40: {
            FIGBHJOFBNE = input.ReadUInt32();
            break;
          }
          case 48: {
            GDGHFKMDIBB = input.ReadUInt32();
            break;
          }
          case 74:
          case 72: {
            avatarList_.AddEntriesFrom(ref input, _repeated_avatarList_codec);
            break;
          }
          case 80: {
            ChallengeId = input.ReadUInt32();
            break;
          }
          case 88: {
            INJIEFFNELN = input.ReadUInt32();
            break;
          }
          case 96: {
            CIHNMECIFNI = input.ReadUInt32();
            break;
          }
          case 106:
          case 104: {
            fCMILJBOHLP_.AddEntriesFrom(ref input, _repeated_fCMILJBOHLP_codec);
            break;
          }
          case 120: {
            BNPOOOEJBMA = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
