// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LJFBDHHDPOM.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from LJFBDHHDPOM.proto</summary>
  public static partial class LJFBDHHDPOMReflection {

    #region Descriptor
    /// <summary>File descriptor for LJFBDHHDPOM.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LJFBDHHDPOMReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMSkZCREhIRFBPTS5wcm90bxoWR2FtZVJvZ3VlTWlyYWNsZS5wcm90byJK",
            "CgtMSkZCREhIRFBPTRITCgtHRU5QSURKS0VGThgOIAEoDRImCgtJTkNFSUhJ",
            "TE5PThgJIAEoCzIRLkdhbWVSb2d1ZU1pcmFjbGVCHqoCG0VnZ0xpbmsuRGFu",
            "aGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.GameRogueMiracleReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.LJFBDHHDPOM), global::EggLink.DanhengServer.Proto.LJFBDHHDPOM.Parser, new[]{ "GENPIDJKEFN", "INCEIHILNON" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LJFBDHHDPOM : pb::IMessage<LJFBDHHDPOM>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LJFBDHHDPOM> _parser = new pb::MessageParser<LJFBDHHDPOM>(() => new LJFBDHHDPOM());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LJFBDHHDPOM> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.LJFBDHHDPOMReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LJFBDHHDPOM() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LJFBDHHDPOM(LJFBDHHDPOM other) : this() {
      gENPIDJKEFN_ = other.gENPIDJKEFN_;
      iNCEIHILNON_ = other.iNCEIHILNON_ != null ? other.iNCEIHILNON_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LJFBDHHDPOM Clone() {
      return new LJFBDHHDPOM(this);
    }

    /// <summary>Field number for the "GENPIDJKEFN" field.</summary>
    public const int GENPIDJKEFNFieldNumber = 14;
    private uint gENPIDJKEFN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GENPIDJKEFN {
      get { return gENPIDJKEFN_; }
      set {
        gENPIDJKEFN_ = value;
      }
    }

    /// <summary>Field number for the "INCEIHILNON" field.</summary>
    public const int INCEIHILNONFieldNumber = 9;
    private global::EggLink.DanhengServer.Proto.GameRogueMiracle iNCEIHILNON_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.GameRogueMiracle INCEIHILNON {
      get { return iNCEIHILNON_; }
      set {
        iNCEIHILNON_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LJFBDHHDPOM);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LJFBDHHDPOM other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GENPIDJKEFN != other.GENPIDJKEFN) return false;
      if (!object.Equals(INCEIHILNON, other.INCEIHILNON)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GENPIDJKEFN != 0) hash ^= GENPIDJKEFN.GetHashCode();
      if (iNCEIHILNON_ != null) hash ^= INCEIHILNON.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (iNCEIHILNON_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(INCEIHILNON);
      }
      if (GENPIDJKEFN != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(GENPIDJKEFN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (iNCEIHILNON_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(INCEIHILNON);
      }
      if (GENPIDJKEFN != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(GENPIDJKEFN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GENPIDJKEFN != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GENPIDJKEFN);
      }
      if (iNCEIHILNON_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(INCEIHILNON);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LJFBDHHDPOM other) {
      if (other == null) {
        return;
      }
      if (other.GENPIDJKEFN != 0) {
        GENPIDJKEFN = other.GENPIDJKEFN;
      }
      if (other.iNCEIHILNON_ != null) {
        if (iNCEIHILNON_ == null) {
          INCEIHILNON = new global::EggLink.DanhengServer.Proto.GameRogueMiracle();
        }
        INCEIHILNON.MergeFrom(other.INCEIHILNON);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 74: {
            if (iNCEIHILNON_ == null) {
              INCEIHILNON = new global::EggLink.DanhengServer.Proto.GameRogueMiracle();
            }
            input.ReadMessage(INCEIHILNON);
            break;
          }
          case 112: {
            GENPIDJKEFN = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 74: {
            if (iNCEIHILNON_ == null) {
              INCEIHILNON = new global::EggLink.DanhengServer.Proto.GameRogueMiracle();
            }
            input.ReadMessage(INCEIHILNON);
            break;
          }
          case 112: {
            GENPIDJKEFN = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
