// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MAAOLKGLLBI.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from MAAOLKGLLBI.proto</summary>
  public static partial class MAAOLKGLLBIReflection {

    #region Descriptor
    /// <summary>File descriptor for MAAOLKGLLBI.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MAAOLKGLLBIReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNQUFPTEtHTExCSS5wcm90byJyCgtNQUFPTEtHTExCSRIQCghhZmZpeF9p",
            "ZBgGIAEoDRITCgtISEVORkdKUEZPQRgCIAEoCBITCgtLS0VBRUJBR01LRRgE",
            "IAEoCBIRCgl1bmlxdWVfaWQYCyABKA0SFAoMbW9uc3Rlcl9saXN0GAggAygN",
            "Qh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.MAAOLKGLLBI), global::EggLink.DanhengServer.Proto.MAAOLKGLLBI.Parser, new[]{ "AffixId", "HHENFGJPFOA", "KKEAEBAGMKE", "UniqueId", "MonsterList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MAAOLKGLLBI : pb::IMessage<MAAOLKGLLBI>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MAAOLKGLLBI> _parser = new pb::MessageParser<MAAOLKGLLBI>(() => new MAAOLKGLLBI());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MAAOLKGLLBI> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.MAAOLKGLLBIReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MAAOLKGLLBI() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MAAOLKGLLBI(MAAOLKGLLBI other) : this() {
      affixId_ = other.affixId_;
      hHENFGJPFOA_ = other.hHENFGJPFOA_;
      kKEAEBAGMKE_ = other.kKEAEBAGMKE_;
      uniqueId_ = other.uniqueId_;
      monsterList_ = other.monsterList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MAAOLKGLLBI Clone() {
      return new MAAOLKGLLBI(this);
    }

    /// <summary>Field number for the "affix_id" field.</summary>
    public const int AffixIdFieldNumber = 6;
    private uint affixId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AffixId {
      get { return affixId_; }
      set {
        affixId_ = value;
      }
    }

    /// <summary>Field number for the "HHENFGJPFOA" field.</summary>
    public const int HHENFGJPFOAFieldNumber = 2;
    private bool hHENFGJPFOA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HHENFGJPFOA {
      get { return hHENFGJPFOA_; }
      set {
        hHENFGJPFOA_ = value;
      }
    }

    /// <summary>Field number for the "KKEAEBAGMKE" field.</summary>
    public const int KKEAEBAGMKEFieldNumber = 4;
    private bool kKEAEBAGMKE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool KKEAEBAGMKE {
      get { return kKEAEBAGMKE_; }
      set {
        kKEAEBAGMKE_ = value;
      }
    }

    /// <summary>Field number for the "unique_id" field.</summary>
    public const int UniqueIdFieldNumber = 11;
    private uint uniqueId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UniqueId {
      get { return uniqueId_; }
      set {
        uniqueId_ = value;
      }
    }

    /// <summary>Field number for the "monster_list" field.</summary>
    public const int MonsterListFieldNumber = 8;
    private static readonly pb::FieldCodec<uint> _repeated_monsterList_codec
        = pb::FieldCodec.ForUInt32(66);
    private readonly pbc::RepeatedField<uint> monsterList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> MonsterList {
      get { return monsterList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MAAOLKGLLBI);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MAAOLKGLLBI other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AffixId != other.AffixId) return false;
      if (HHENFGJPFOA != other.HHENFGJPFOA) return false;
      if (KKEAEBAGMKE != other.KKEAEBAGMKE) return false;
      if (UniqueId != other.UniqueId) return false;
      if(!monsterList_.Equals(other.monsterList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AffixId != 0) hash ^= AffixId.GetHashCode();
      if (HHENFGJPFOA != false) hash ^= HHENFGJPFOA.GetHashCode();
      if (KKEAEBAGMKE != false) hash ^= KKEAEBAGMKE.GetHashCode();
      if (UniqueId != 0) hash ^= UniqueId.GetHashCode();
      hash ^= monsterList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HHENFGJPFOA != false) {
        output.WriteRawTag(16);
        output.WriteBool(HHENFGJPFOA);
      }
      if (KKEAEBAGMKE != false) {
        output.WriteRawTag(32);
        output.WriteBool(KKEAEBAGMKE);
      }
      if (AffixId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(AffixId);
      }
      monsterList_.WriteTo(output, _repeated_monsterList_codec);
      if (UniqueId != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(UniqueId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HHENFGJPFOA != false) {
        output.WriteRawTag(16);
        output.WriteBool(HHENFGJPFOA);
      }
      if (KKEAEBAGMKE != false) {
        output.WriteRawTag(32);
        output.WriteBool(KKEAEBAGMKE);
      }
      if (AffixId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(AffixId);
      }
      monsterList_.WriteTo(ref output, _repeated_monsterList_codec);
      if (UniqueId != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(UniqueId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AffixId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AffixId);
      }
      if (HHENFGJPFOA != false) {
        size += 1 + 1;
      }
      if (KKEAEBAGMKE != false) {
        size += 1 + 1;
      }
      if (UniqueId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UniqueId);
      }
      size += monsterList_.CalculateSize(_repeated_monsterList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MAAOLKGLLBI other) {
      if (other == null) {
        return;
      }
      if (other.AffixId != 0) {
        AffixId = other.AffixId;
      }
      if (other.HHENFGJPFOA != false) {
        HHENFGJPFOA = other.HHENFGJPFOA;
      }
      if (other.KKEAEBAGMKE != false) {
        KKEAEBAGMKE = other.KKEAEBAGMKE;
      }
      if (other.UniqueId != 0) {
        UniqueId = other.UniqueId;
      }
      monsterList_.Add(other.monsterList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            HHENFGJPFOA = input.ReadBool();
            break;
          }
          case 32: {
            KKEAEBAGMKE = input.ReadBool();
            break;
          }
          case 48: {
            AffixId = input.ReadUInt32();
            break;
          }
          case 66:
          case 64: {
            monsterList_.AddEntriesFrom(input, _repeated_monsterList_codec);
            break;
          }
          case 88: {
            UniqueId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            HHENFGJPFOA = input.ReadBool();
            break;
          }
          case 32: {
            KKEAEBAGMKE = input.ReadBool();
            break;
          }
          case 48: {
            AffixId = input.ReadUInt32();
            break;
          }
          case 66:
          case 64: {
            monsterList_.AddEntriesFrom(ref input, _repeated_monsterList_codec);
            break;
          }
          case 88: {
            UniqueId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
