// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MonopolyGetDailyInitItemScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from MonopolyGetDailyInitItemScRsp.proto</summary>
  public static partial class MonopolyGetDailyInitItemScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for MonopolyGetDailyInitItemScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MonopolyGetDailyInitItemScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNNb25vcG9seUdldERhaWx5SW5pdEl0ZW1TY1JzcC5wcm90byKuAQodTW9u",
            "b3BvbHlHZXREYWlseUluaXRJdGVtU2NSc3ASEwoLRFBPTU1JRUJLRk8YASAB",
            "KA0SEwoLRkdDSE1DQ0hFT0QYCSABKA0SEwoLT0hFS0tJSEVKSU8YDyABKA0S",
            "EwoLR09BQkVIT09FQkoYBCABKA0SDwoHcmV0Y29kZRgIIAEoDRITCgtLSUtE",
            "SkJFRElNQhgLIAEoDRITCgtJRUtIRklMSERQRxgFIAEoA0IeqgIbRWdnTGlu",
            "ay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.MonopolyGetDailyInitItemScRsp), global::EggLink.DanhengServer.Proto.MonopolyGetDailyInitItemScRsp.Parser, new[]{ "DPOMMIEBKFO", "FGCHMCCHEOD", "OHEKKIHEJIO", "GOABEHOOEBJ", "Retcode", "KIKDJBEDIMB", "IEKHFILHDPG" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MonopolyGetDailyInitItemScRsp : pb::IMessage<MonopolyGetDailyInitItemScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MonopolyGetDailyInitItemScRsp> _parser = new pb::MessageParser<MonopolyGetDailyInitItemScRsp>(() => new MonopolyGetDailyInitItemScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MonopolyGetDailyInitItemScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.MonopolyGetDailyInitItemScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonopolyGetDailyInitItemScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonopolyGetDailyInitItemScRsp(MonopolyGetDailyInitItemScRsp other) : this() {
      dPOMMIEBKFO_ = other.dPOMMIEBKFO_;
      fGCHMCCHEOD_ = other.fGCHMCCHEOD_;
      oHEKKIHEJIO_ = other.oHEKKIHEJIO_;
      gOABEHOOEBJ_ = other.gOABEHOOEBJ_;
      retcode_ = other.retcode_;
      kIKDJBEDIMB_ = other.kIKDJBEDIMB_;
      iEKHFILHDPG_ = other.iEKHFILHDPG_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonopolyGetDailyInitItemScRsp Clone() {
      return new MonopolyGetDailyInitItemScRsp(this);
    }

    /// <summary>Field number for the "DPOMMIEBKFO" field.</summary>
    public const int DPOMMIEBKFOFieldNumber = 1;
    private uint dPOMMIEBKFO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DPOMMIEBKFO {
      get { return dPOMMIEBKFO_; }
      set {
        dPOMMIEBKFO_ = value;
      }
    }

    /// <summary>Field number for the "FGCHMCCHEOD" field.</summary>
    public const int FGCHMCCHEODFieldNumber = 9;
    private uint fGCHMCCHEOD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FGCHMCCHEOD {
      get { return fGCHMCCHEOD_; }
      set {
        fGCHMCCHEOD_ = value;
      }
    }

    /// <summary>Field number for the "OHEKKIHEJIO" field.</summary>
    public const int OHEKKIHEJIOFieldNumber = 15;
    private uint oHEKKIHEJIO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint OHEKKIHEJIO {
      get { return oHEKKIHEJIO_; }
      set {
        oHEKKIHEJIO_ = value;
      }
    }

    /// <summary>Field number for the "GOABEHOOEBJ" field.</summary>
    public const int GOABEHOOEBJFieldNumber = 4;
    private uint gOABEHOOEBJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GOABEHOOEBJ {
      get { return gOABEHOOEBJ_; }
      set {
        gOABEHOOEBJ_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 8;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "KIKDJBEDIMB" field.</summary>
    public const int KIKDJBEDIMBFieldNumber = 11;
    private uint kIKDJBEDIMB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KIKDJBEDIMB {
      get { return kIKDJBEDIMB_; }
      set {
        kIKDJBEDIMB_ = value;
      }
    }

    /// <summary>Field number for the "IEKHFILHDPG" field.</summary>
    public const int IEKHFILHDPGFieldNumber = 5;
    private long iEKHFILHDPG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IEKHFILHDPG {
      get { return iEKHFILHDPG_; }
      set {
        iEKHFILHDPG_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MonopolyGetDailyInitItemScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MonopolyGetDailyInitItemScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DPOMMIEBKFO != other.DPOMMIEBKFO) return false;
      if (FGCHMCCHEOD != other.FGCHMCCHEOD) return false;
      if (OHEKKIHEJIO != other.OHEKKIHEJIO) return false;
      if (GOABEHOOEBJ != other.GOABEHOOEBJ) return false;
      if (Retcode != other.Retcode) return false;
      if (KIKDJBEDIMB != other.KIKDJBEDIMB) return false;
      if (IEKHFILHDPG != other.IEKHFILHDPG) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DPOMMIEBKFO != 0) hash ^= DPOMMIEBKFO.GetHashCode();
      if (FGCHMCCHEOD != 0) hash ^= FGCHMCCHEOD.GetHashCode();
      if (OHEKKIHEJIO != 0) hash ^= OHEKKIHEJIO.GetHashCode();
      if (GOABEHOOEBJ != 0) hash ^= GOABEHOOEBJ.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (KIKDJBEDIMB != 0) hash ^= KIKDJBEDIMB.GetHashCode();
      if (IEKHFILHDPG != 0L) hash ^= IEKHFILHDPG.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DPOMMIEBKFO != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(DPOMMIEBKFO);
      }
      if (GOABEHOOEBJ != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(GOABEHOOEBJ);
      }
      if (IEKHFILHDPG != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(IEKHFILHDPG);
      }
      if (Retcode != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Retcode);
      }
      if (FGCHMCCHEOD != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(FGCHMCCHEOD);
      }
      if (KIKDJBEDIMB != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(KIKDJBEDIMB);
      }
      if (OHEKKIHEJIO != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(OHEKKIHEJIO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DPOMMIEBKFO != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(DPOMMIEBKFO);
      }
      if (GOABEHOOEBJ != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(GOABEHOOEBJ);
      }
      if (IEKHFILHDPG != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(IEKHFILHDPG);
      }
      if (Retcode != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Retcode);
      }
      if (FGCHMCCHEOD != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(FGCHMCCHEOD);
      }
      if (KIKDJBEDIMB != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(KIKDJBEDIMB);
      }
      if (OHEKKIHEJIO != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(OHEKKIHEJIO);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DPOMMIEBKFO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DPOMMIEBKFO);
      }
      if (FGCHMCCHEOD != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FGCHMCCHEOD);
      }
      if (OHEKKIHEJIO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OHEKKIHEJIO);
      }
      if (GOABEHOOEBJ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GOABEHOOEBJ);
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (KIKDJBEDIMB != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KIKDJBEDIMB);
      }
      if (IEKHFILHDPG != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IEKHFILHDPG);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MonopolyGetDailyInitItemScRsp other) {
      if (other == null) {
        return;
      }
      if (other.DPOMMIEBKFO != 0) {
        DPOMMIEBKFO = other.DPOMMIEBKFO;
      }
      if (other.FGCHMCCHEOD != 0) {
        FGCHMCCHEOD = other.FGCHMCCHEOD;
      }
      if (other.OHEKKIHEJIO != 0) {
        OHEKKIHEJIO = other.OHEKKIHEJIO;
      }
      if (other.GOABEHOOEBJ != 0) {
        GOABEHOOEBJ = other.GOABEHOOEBJ;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.KIKDJBEDIMB != 0) {
        KIKDJBEDIMB = other.KIKDJBEDIMB;
      }
      if (other.IEKHFILHDPG != 0L) {
        IEKHFILHDPG = other.IEKHFILHDPG;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DPOMMIEBKFO = input.ReadUInt32();
            break;
          }
          case 32: {
            GOABEHOOEBJ = input.ReadUInt32();
            break;
          }
          case 40: {
            IEKHFILHDPG = input.ReadInt64();
            break;
          }
          case 64: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 72: {
            FGCHMCCHEOD = input.ReadUInt32();
            break;
          }
          case 88: {
            KIKDJBEDIMB = input.ReadUInt32();
            break;
          }
          case 120: {
            OHEKKIHEJIO = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DPOMMIEBKFO = input.ReadUInt32();
            break;
          }
          case 32: {
            GOABEHOOEBJ = input.ReadUInt32();
            break;
          }
          case 40: {
            IEKHFILHDPG = input.ReadInt64();
            break;
          }
          case 64: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 72: {
            FGCHMCCHEOD = input.ReadUInt32();
            break;
          }
          case 88: {
            KIKDJBEDIMB = input.ReadUInt32();
            break;
          }
          case 120: {
            OHEKKIHEJIO = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
