// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MultipleDropInfoNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from MultipleDropInfoNotify.proto</summary>
  public static partial class MultipleDropInfoNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for MultipleDropInfoNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MultipleDropInfoNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxNdWx0aXBsZURyb3BJbmZvTm90aWZ5LnByb3RvGhFKTUxCSkNMRE1MRy5w",
            "cm90bxoRSExJT09OSkhHTkwucHJvdG8aEVBISEtQSkpETERKLnByb3RvIoEB",
            "ChZNdWx0aXBsZURyb3BJbmZvTm90aWZ5EiEKC0lKQlBNQUxNQUdHGAYgAygL",
            "MgwuSk1MQkpDTERNTEcSIQoLS09HQk1JT0tHR0wYCCADKAsyDC5ITElPT05K",
            "SEdOTBIhCgtBRkhIRk5HRklGRBgNIAMoCzIMLlBISEtQSkpETERKQh6qAhtF",
            "Z2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.JMLBJCLDMLGReflection.Descriptor, global::EggLink.DanhengServer.Proto.HLIOONJHGNLReflection.Descriptor, global::EggLink.DanhengServer.Proto.PHHKPJJDLDJReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.MultipleDropInfoNotify), global::EggLink.DanhengServer.Proto.MultipleDropInfoNotify.Parser, new[]{ "IJBPMALMAGG", "KOGBMIOKGGL", "AFHHFNGFIFD" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MultipleDropInfoNotify : pb::IMessage<MultipleDropInfoNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MultipleDropInfoNotify> _parser = new pb::MessageParser<MultipleDropInfoNotify>(() => new MultipleDropInfoNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MultipleDropInfoNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.MultipleDropInfoNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultipleDropInfoNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultipleDropInfoNotify(MultipleDropInfoNotify other) : this() {
      iJBPMALMAGG_ = other.iJBPMALMAGG_.Clone();
      kOGBMIOKGGL_ = other.kOGBMIOKGGL_.Clone();
      aFHHFNGFIFD_ = other.aFHHFNGFIFD_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultipleDropInfoNotify Clone() {
      return new MultipleDropInfoNotify(this);
    }

    /// <summary>Field number for the "IJBPMALMAGG" field.</summary>
    public const int IJBPMALMAGGFieldNumber = 6;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.JMLBJCLDMLG> _repeated_iJBPMALMAGG_codec
        = pb::FieldCodec.ForMessage(50, global::EggLink.DanhengServer.Proto.JMLBJCLDMLG.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JMLBJCLDMLG> iJBPMALMAGG_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JMLBJCLDMLG>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JMLBJCLDMLG> IJBPMALMAGG {
      get { return iJBPMALMAGG_; }
    }

    /// <summary>Field number for the "KOGBMIOKGGL" field.</summary>
    public const int KOGBMIOKGGLFieldNumber = 8;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.HLIOONJHGNL> _repeated_kOGBMIOKGGL_codec
        = pb::FieldCodec.ForMessage(66, global::EggLink.DanhengServer.Proto.HLIOONJHGNL.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HLIOONJHGNL> kOGBMIOKGGL_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HLIOONJHGNL>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HLIOONJHGNL> KOGBMIOKGGL {
      get { return kOGBMIOKGGL_; }
    }

    /// <summary>Field number for the "AFHHFNGFIFD" field.</summary>
    public const int AFHHFNGFIFDFieldNumber = 13;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.PHHKPJJDLDJ> _repeated_aFHHFNGFIFD_codec
        = pb::FieldCodec.ForMessage(106, global::EggLink.DanhengServer.Proto.PHHKPJJDLDJ.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PHHKPJJDLDJ> aFHHFNGFIFD_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PHHKPJJDLDJ>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PHHKPJJDLDJ> AFHHFNGFIFD {
      get { return aFHHFNGFIFD_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MultipleDropInfoNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MultipleDropInfoNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!iJBPMALMAGG_.Equals(other.iJBPMALMAGG_)) return false;
      if(!kOGBMIOKGGL_.Equals(other.kOGBMIOKGGL_)) return false;
      if(!aFHHFNGFIFD_.Equals(other.aFHHFNGFIFD_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= iJBPMALMAGG_.GetHashCode();
      hash ^= kOGBMIOKGGL_.GetHashCode();
      hash ^= aFHHFNGFIFD_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      iJBPMALMAGG_.WriteTo(output, _repeated_iJBPMALMAGG_codec);
      kOGBMIOKGGL_.WriteTo(output, _repeated_kOGBMIOKGGL_codec);
      aFHHFNGFIFD_.WriteTo(output, _repeated_aFHHFNGFIFD_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      iJBPMALMAGG_.WriteTo(ref output, _repeated_iJBPMALMAGG_codec);
      kOGBMIOKGGL_.WriteTo(ref output, _repeated_kOGBMIOKGGL_codec);
      aFHHFNGFIFD_.WriteTo(ref output, _repeated_aFHHFNGFIFD_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += iJBPMALMAGG_.CalculateSize(_repeated_iJBPMALMAGG_codec);
      size += kOGBMIOKGGL_.CalculateSize(_repeated_kOGBMIOKGGL_codec);
      size += aFHHFNGFIFD_.CalculateSize(_repeated_aFHHFNGFIFD_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MultipleDropInfoNotify other) {
      if (other == null) {
        return;
      }
      iJBPMALMAGG_.Add(other.iJBPMALMAGG_);
      kOGBMIOKGGL_.Add(other.kOGBMIOKGGL_);
      aFHHFNGFIFD_.Add(other.aFHHFNGFIFD_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 50: {
            iJBPMALMAGG_.AddEntriesFrom(input, _repeated_iJBPMALMAGG_codec);
            break;
          }
          case 66: {
            kOGBMIOKGGL_.AddEntriesFrom(input, _repeated_kOGBMIOKGGL_codec);
            break;
          }
          case 106: {
            aFHHFNGFIFD_.AddEntriesFrom(input, _repeated_aFHHFNGFIFD_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 50: {
            iJBPMALMAGG_.AddEntriesFrom(ref input, _repeated_iJBPMALMAGG_codec);
            break;
          }
          case 66: {
            kOGBMIOKGGL_.AddEntriesFrom(ref input, _repeated_kOGBMIOKGGL_codec);
            break;
          }
          case 106: {
            aFHHFNGFIFD_.AddEntriesFrom(ref input, _repeated_aFHHFNGFIFD_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
