// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OLMNOHDHFHN.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from OLMNOHDHFHN.proto</summary>
  public static partial class OLMNOHDHFHNReflection {

    #region Descriptor
    /// <summary>File descriptor for OLMNOHDHFHN.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OLMNOHDHFHNReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFPTE1OT0hESEZITi5wcm90byJyCgtPTE1OT0hESEZIThITCgtBQlBFT01D",
            "Rk1BQhgEIAEoDRITCgtDSUREQ0dIRkZPQxgBIAEoDRITCgtCTEhLTkdNQVBJ",
            "TxgGIAEoDRITCgtDQ01HRkZLUEpJRhgCIAEoDRIPCgdidWZmX2lkGA0gASgN",
            "Qh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.OLMNOHDHFHN), global::EggLink.DanhengServer.Proto.OLMNOHDHFHN.Parser, new[]{ "ABPEOMCFMAB", "CIDDCGHFFOC", "BLHKNGMAPIO", "CCMGFFKPJIF", "BuffId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OLMNOHDHFHN : pb::IMessage<OLMNOHDHFHN>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OLMNOHDHFHN> _parser = new pb::MessageParser<OLMNOHDHFHN>(() => new OLMNOHDHFHN());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OLMNOHDHFHN> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.OLMNOHDHFHNReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OLMNOHDHFHN() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OLMNOHDHFHN(OLMNOHDHFHN other) : this() {
      aBPEOMCFMAB_ = other.aBPEOMCFMAB_;
      cIDDCGHFFOC_ = other.cIDDCGHFFOC_;
      bLHKNGMAPIO_ = other.bLHKNGMAPIO_;
      cCMGFFKPJIF_ = other.cCMGFFKPJIF_;
      buffId_ = other.buffId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OLMNOHDHFHN Clone() {
      return new OLMNOHDHFHN(this);
    }

    /// <summary>Field number for the "ABPEOMCFMAB" field.</summary>
    public const int ABPEOMCFMABFieldNumber = 4;
    private uint aBPEOMCFMAB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ABPEOMCFMAB {
      get { return aBPEOMCFMAB_; }
      set {
        aBPEOMCFMAB_ = value;
      }
    }

    /// <summary>Field number for the "CIDDCGHFFOC" field.</summary>
    public const int CIDDCGHFFOCFieldNumber = 1;
    private uint cIDDCGHFFOC_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CIDDCGHFFOC {
      get { return cIDDCGHFFOC_; }
      set {
        cIDDCGHFFOC_ = value;
      }
    }

    /// <summary>Field number for the "BLHKNGMAPIO" field.</summary>
    public const int BLHKNGMAPIOFieldNumber = 6;
    private uint bLHKNGMAPIO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BLHKNGMAPIO {
      get { return bLHKNGMAPIO_; }
      set {
        bLHKNGMAPIO_ = value;
      }
    }

    /// <summary>Field number for the "CCMGFFKPJIF" field.</summary>
    public const int CCMGFFKPJIFFieldNumber = 2;
    private uint cCMGFFKPJIF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CCMGFFKPJIF {
      get { return cCMGFFKPJIF_; }
      set {
        cCMGFFKPJIF_ = value;
      }
    }

    /// <summary>Field number for the "buff_id" field.</summary>
    public const int BuffIdFieldNumber = 13;
    private uint buffId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BuffId {
      get { return buffId_; }
      set {
        buffId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OLMNOHDHFHN);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OLMNOHDHFHN other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ABPEOMCFMAB != other.ABPEOMCFMAB) return false;
      if (CIDDCGHFFOC != other.CIDDCGHFFOC) return false;
      if (BLHKNGMAPIO != other.BLHKNGMAPIO) return false;
      if (CCMGFFKPJIF != other.CCMGFFKPJIF) return false;
      if (BuffId != other.BuffId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ABPEOMCFMAB != 0) hash ^= ABPEOMCFMAB.GetHashCode();
      if (CIDDCGHFFOC != 0) hash ^= CIDDCGHFFOC.GetHashCode();
      if (BLHKNGMAPIO != 0) hash ^= BLHKNGMAPIO.GetHashCode();
      if (CCMGFFKPJIF != 0) hash ^= CCMGFFKPJIF.GetHashCode();
      if (BuffId != 0) hash ^= BuffId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CIDDCGHFFOC != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(CIDDCGHFFOC);
      }
      if (CCMGFFKPJIF != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(CCMGFFKPJIF);
      }
      if (ABPEOMCFMAB != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(ABPEOMCFMAB);
      }
      if (BLHKNGMAPIO != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(BLHKNGMAPIO);
      }
      if (BuffId != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(BuffId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CIDDCGHFFOC != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(CIDDCGHFFOC);
      }
      if (CCMGFFKPJIF != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(CCMGFFKPJIF);
      }
      if (ABPEOMCFMAB != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(ABPEOMCFMAB);
      }
      if (BLHKNGMAPIO != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(BLHKNGMAPIO);
      }
      if (BuffId != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(BuffId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ABPEOMCFMAB != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ABPEOMCFMAB);
      }
      if (CIDDCGHFFOC != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CIDDCGHFFOC);
      }
      if (BLHKNGMAPIO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BLHKNGMAPIO);
      }
      if (CCMGFFKPJIF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CCMGFFKPJIF);
      }
      if (BuffId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BuffId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OLMNOHDHFHN other) {
      if (other == null) {
        return;
      }
      if (other.ABPEOMCFMAB != 0) {
        ABPEOMCFMAB = other.ABPEOMCFMAB;
      }
      if (other.CIDDCGHFFOC != 0) {
        CIDDCGHFFOC = other.CIDDCGHFFOC;
      }
      if (other.BLHKNGMAPIO != 0) {
        BLHKNGMAPIO = other.BLHKNGMAPIO;
      }
      if (other.CCMGFFKPJIF != 0) {
        CCMGFFKPJIF = other.CCMGFFKPJIF;
      }
      if (other.BuffId != 0) {
        BuffId = other.BuffId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CIDDCGHFFOC = input.ReadUInt32();
            break;
          }
          case 16: {
            CCMGFFKPJIF = input.ReadUInt32();
            break;
          }
          case 32: {
            ABPEOMCFMAB = input.ReadUInt32();
            break;
          }
          case 48: {
            BLHKNGMAPIO = input.ReadUInt32();
            break;
          }
          case 104: {
            BuffId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CIDDCGHFFOC = input.ReadUInt32();
            break;
          }
          case 16: {
            CCMGFFKPJIF = input.ReadUInt32();
            break;
          }
          case 32: {
            ABPEOMCFMAB = input.ReadUInt32();
            break;
          }
          case 48: {
            BLHKNGMAPIO = input.ReadUInt32();
            break;
          }
          case 104: {
            BuffId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
