// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlanetFesGetOfferedCardPieceScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from PlanetFesGetOfferedCardPieceScRsp.proto</summary>
  public static partial class PlanetFesGetOfferedCardPieceScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for PlanetFesGetOfferedCardPieceScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlanetFesGetOfferedCardPieceScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidQbGFuZXRGZXNHZXRPZmZlcmVkQ2FyZFBpZWNlU2NSc3AucHJvdG8aEUNF",
            "T0REQ0VJRERMLnByb3RvGhFCS0JJTFBES09JTC5wcm90byK5AQohUGxhbmV0",
            "RmVzR2V0T2ZmZXJlZENhcmRQaWVjZVNjUnNwEhMKC0hQSkpEQ0pISE9BGAMg",
            "ASgEEhMKC0NBQkVIS09GTFBHGAggASgIEiEKC09OSkdNR0hDUEVGGAQgAygL",
            "MgwuQktCSUxQREtPSUwSIQoLUEJGSEROQkdNQlAYByADKAsyDC5DRU9ERENF",
            "SURETBITCgtETEpDS0NNQURIShgNIAEoAxIPCgdyZXRjb2RlGAkgASgNQh6q",
            "AhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.CEODDCEIDDLReflection.Descriptor, global::EggLink.DanhengServer.Proto.BKBILPDKOILReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.PlanetFesGetOfferedCardPieceScRsp), global::EggLink.DanhengServer.Proto.PlanetFesGetOfferedCardPieceScRsp.Parser, new[]{ "HPJJDCJHHOA", "CABEHKOFLPG", "ONJGMGHCPEF", "PBFHDNBGMBP", "DLJCKCMADHJ", "Retcode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlanetFesGetOfferedCardPieceScRsp : pb::IMessage<PlanetFesGetOfferedCardPieceScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlanetFesGetOfferedCardPieceScRsp> _parser = new pb::MessageParser<PlanetFesGetOfferedCardPieceScRsp>(() => new PlanetFesGetOfferedCardPieceScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlanetFesGetOfferedCardPieceScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.PlanetFesGetOfferedCardPieceScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanetFesGetOfferedCardPieceScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanetFesGetOfferedCardPieceScRsp(PlanetFesGetOfferedCardPieceScRsp other) : this() {
      hPJJDCJHHOA_ = other.hPJJDCJHHOA_;
      cABEHKOFLPG_ = other.cABEHKOFLPG_;
      oNJGMGHCPEF_ = other.oNJGMGHCPEF_.Clone();
      pBFHDNBGMBP_ = other.pBFHDNBGMBP_.Clone();
      dLJCKCMADHJ_ = other.dLJCKCMADHJ_;
      retcode_ = other.retcode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanetFesGetOfferedCardPieceScRsp Clone() {
      return new PlanetFesGetOfferedCardPieceScRsp(this);
    }

    /// <summary>Field number for the "HPJJDCJHHOA" field.</summary>
    public const int HPJJDCJHHOAFieldNumber = 3;
    private ulong hPJJDCJHHOA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong HPJJDCJHHOA {
      get { return hPJJDCJHHOA_; }
      set {
        hPJJDCJHHOA_ = value;
      }
    }

    /// <summary>Field number for the "CABEHKOFLPG" field.</summary>
    public const int CABEHKOFLPGFieldNumber = 8;
    private bool cABEHKOFLPG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CABEHKOFLPG {
      get { return cABEHKOFLPG_; }
      set {
        cABEHKOFLPG_ = value;
      }
    }

    /// <summary>Field number for the "ONJGMGHCPEF" field.</summary>
    public const int ONJGMGHCPEFFieldNumber = 4;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.BKBILPDKOIL> _repeated_oNJGMGHCPEF_codec
        = pb::FieldCodec.ForMessage(34, global::EggLink.DanhengServer.Proto.BKBILPDKOIL.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.BKBILPDKOIL> oNJGMGHCPEF_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.BKBILPDKOIL>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.BKBILPDKOIL> ONJGMGHCPEF {
      get { return oNJGMGHCPEF_; }
    }

    /// <summary>Field number for the "PBFHDNBGMBP" field.</summary>
    public const int PBFHDNBGMBPFieldNumber = 7;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.CEODDCEIDDL> _repeated_pBFHDNBGMBP_codec
        = pb::FieldCodec.ForMessage(58, global::EggLink.DanhengServer.Proto.CEODDCEIDDL.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.CEODDCEIDDL> pBFHDNBGMBP_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.CEODDCEIDDL>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.CEODDCEIDDL> PBFHDNBGMBP {
      get { return pBFHDNBGMBP_; }
    }

    /// <summary>Field number for the "DLJCKCMADHJ" field.</summary>
    public const int DLJCKCMADHJFieldNumber = 13;
    private long dLJCKCMADHJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DLJCKCMADHJ {
      get { return dLJCKCMADHJ_; }
      set {
        dLJCKCMADHJ_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 9;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlanetFesGetOfferedCardPieceScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlanetFesGetOfferedCardPieceScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HPJJDCJHHOA != other.HPJJDCJHHOA) return false;
      if (CABEHKOFLPG != other.CABEHKOFLPG) return false;
      if(!oNJGMGHCPEF_.Equals(other.oNJGMGHCPEF_)) return false;
      if(!pBFHDNBGMBP_.Equals(other.pBFHDNBGMBP_)) return false;
      if (DLJCKCMADHJ != other.DLJCKCMADHJ) return false;
      if (Retcode != other.Retcode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HPJJDCJHHOA != 0UL) hash ^= HPJJDCJHHOA.GetHashCode();
      if (CABEHKOFLPG != false) hash ^= CABEHKOFLPG.GetHashCode();
      hash ^= oNJGMGHCPEF_.GetHashCode();
      hash ^= pBFHDNBGMBP_.GetHashCode();
      if (DLJCKCMADHJ != 0L) hash ^= DLJCKCMADHJ.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HPJJDCJHHOA != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(HPJJDCJHHOA);
      }
      oNJGMGHCPEF_.WriteTo(output, _repeated_oNJGMGHCPEF_codec);
      pBFHDNBGMBP_.WriteTo(output, _repeated_pBFHDNBGMBP_codec);
      if (CABEHKOFLPG != false) {
        output.WriteRawTag(64);
        output.WriteBool(CABEHKOFLPG);
      }
      if (Retcode != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Retcode);
      }
      if (DLJCKCMADHJ != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(DLJCKCMADHJ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HPJJDCJHHOA != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(HPJJDCJHHOA);
      }
      oNJGMGHCPEF_.WriteTo(ref output, _repeated_oNJGMGHCPEF_codec);
      pBFHDNBGMBP_.WriteTo(ref output, _repeated_pBFHDNBGMBP_codec);
      if (CABEHKOFLPG != false) {
        output.WriteRawTag(64);
        output.WriteBool(CABEHKOFLPG);
      }
      if (Retcode != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Retcode);
      }
      if (DLJCKCMADHJ != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(DLJCKCMADHJ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HPJJDCJHHOA != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(HPJJDCJHHOA);
      }
      if (CABEHKOFLPG != false) {
        size += 1 + 1;
      }
      size += oNJGMGHCPEF_.CalculateSize(_repeated_oNJGMGHCPEF_codec);
      size += pBFHDNBGMBP_.CalculateSize(_repeated_pBFHDNBGMBP_codec);
      if (DLJCKCMADHJ != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DLJCKCMADHJ);
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlanetFesGetOfferedCardPieceScRsp other) {
      if (other == null) {
        return;
      }
      if (other.HPJJDCJHHOA != 0UL) {
        HPJJDCJHHOA = other.HPJJDCJHHOA;
      }
      if (other.CABEHKOFLPG != false) {
        CABEHKOFLPG = other.CABEHKOFLPG;
      }
      oNJGMGHCPEF_.Add(other.oNJGMGHCPEF_);
      pBFHDNBGMBP_.Add(other.pBFHDNBGMBP_);
      if (other.DLJCKCMADHJ != 0L) {
        DLJCKCMADHJ = other.DLJCKCMADHJ;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            HPJJDCJHHOA = input.ReadUInt64();
            break;
          }
          case 34: {
            oNJGMGHCPEF_.AddEntriesFrom(input, _repeated_oNJGMGHCPEF_codec);
            break;
          }
          case 58: {
            pBFHDNBGMBP_.AddEntriesFrom(input, _repeated_pBFHDNBGMBP_codec);
            break;
          }
          case 64: {
            CABEHKOFLPG = input.ReadBool();
            break;
          }
          case 72: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 104: {
            DLJCKCMADHJ = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            HPJJDCJHHOA = input.ReadUInt64();
            break;
          }
          case 34: {
            oNJGMGHCPEF_.AddEntriesFrom(ref input, _repeated_oNJGMGHCPEF_codec);
            break;
          }
          case 58: {
            pBFHDNBGMBP_.AddEntriesFrom(ref input, _repeated_pBFHDNBGMBP_codec);
            break;
          }
          case 64: {
            CABEHKOFLPG = input.ReadBool();
            break;
          }
          case 72: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 104: {
            DLJCKCMADHJ = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
