// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Relic.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from Relic.proto</summary>
  public static partial class RelicReflection {

    #region Descriptor
    /// <summary>File descriptor for Relic.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RelicReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtSZWxpYy5wcm90bxoQUmVsaWNBZmZpeC5wcm90byLEAQoFUmVsaWMSFwoP",
            "ZHJlc3NfYXZhdGFyX2lkGAggASgNEg0KBWxldmVsGAcgASgNEhUKDW1haW5f",
            "YWZmaXhfaWQYBiABKA0SEQoJdW5pcXVlX2lkGAsgASgNEgsKA3RpZBgBIAEo",
            "DRIjCg5zdWJfYWZmaXhfbGlzdBgFIAMoCzILLlJlbGljQWZmaXgSFAoMaXNf",
            "ZGlzY2FyZGVkGA0gASgIEgsKA2V4cBgOIAEoDRIUCgxpc19wcm90ZWN0ZWQY",
            "DyABKAhCHqoCG0VnZ0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.RelicAffixReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.Relic), global::EggLink.DanhengServer.Proto.Relic.Parser, new[]{ "DressAvatarId", "Level", "MainAffixId", "UniqueId", "Tid", "SubAffixList", "IsDiscarded", "Exp", "IsProtected" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Relic : pb::IMessage<Relic>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Relic> _parser = new pb::MessageParser<Relic>(() => new Relic());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Relic> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.RelicReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Relic() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Relic(Relic other) : this() {
      dressAvatarId_ = other.dressAvatarId_;
      level_ = other.level_;
      mainAffixId_ = other.mainAffixId_;
      uniqueId_ = other.uniqueId_;
      tid_ = other.tid_;
      subAffixList_ = other.subAffixList_.Clone();
      isDiscarded_ = other.isDiscarded_;
      exp_ = other.exp_;
      isProtected_ = other.isProtected_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Relic Clone() {
      return new Relic(this);
    }

    /// <summary>Field number for the "dress_avatar_id" field.</summary>
    public const int DressAvatarIdFieldNumber = 8;
    private uint dressAvatarId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DressAvatarId {
      get { return dressAvatarId_; }
      set {
        dressAvatarId_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 7;
    private uint level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "main_affix_id" field.</summary>
    public const int MainAffixIdFieldNumber = 6;
    private uint mainAffixId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MainAffixId {
      get { return mainAffixId_; }
      set {
        mainAffixId_ = value;
      }
    }

    /// <summary>Field number for the "unique_id" field.</summary>
    public const int UniqueIdFieldNumber = 11;
    private uint uniqueId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UniqueId {
      get { return uniqueId_; }
      set {
        uniqueId_ = value;
      }
    }

    /// <summary>Field number for the "tid" field.</summary>
    public const int TidFieldNumber = 1;
    private uint tid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Tid {
      get { return tid_; }
      set {
        tid_ = value;
      }
    }

    /// <summary>Field number for the "sub_affix_list" field.</summary>
    public const int SubAffixListFieldNumber = 5;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.RelicAffix> _repeated_subAffixList_codec
        = pb::FieldCodec.ForMessage(42, global::EggLink.DanhengServer.Proto.RelicAffix.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.RelicAffix> subAffixList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.RelicAffix>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.RelicAffix> SubAffixList {
      get { return subAffixList_; }
    }

    /// <summary>Field number for the "is_discarded" field.</summary>
    public const int IsDiscardedFieldNumber = 13;
    private bool isDiscarded_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsDiscarded {
      get { return isDiscarded_; }
      set {
        isDiscarded_ = value;
      }
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 14;
    private uint exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    /// <summary>Field number for the "is_protected" field.</summary>
    public const int IsProtectedFieldNumber = 15;
    private bool isProtected_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsProtected {
      get { return isProtected_; }
      set {
        isProtected_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Relic);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Relic other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DressAvatarId != other.DressAvatarId) return false;
      if (Level != other.Level) return false;
      if (MainAffixId != other.MainAffixId) return false;
      if (UniqueId != other.UniqueId) return false;
      if (Tid != other.Tid) return false;
      if(!subAffixList_.Equals(other.subAffixList_)) return false;
      if (IsDiscarded != other.IsDiscarded) return false;
      if (Exp != other.Exp) return false;
      if (IsProtected != other.IsProtected) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DressAvatarId != 0) hash ^= DressAvatarId.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (MainAffixId != 0) hash ^= MainAffixId.GetHashCode();
      if (UniqueId != 0) hash ^= UniqueId.GetHashCode();
      if (Tid != 0) hash ^= Tid.GetHashCode();
      hash ^= subAffixList_.GetHashCode();
      if (IsDiscarded != false) hash ^= IsDiscarded.GetHashCode();
      if (Exp != 0) hash ^= Exp.GetHashCode();
      if (IsProtected != false) hash ^= IsProtected.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Tid != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Tid);
      }
      subAffixList_.WriteTo(output, _repeated_subAffixList_codec);
      if (MainAffixId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(MainAffixId);
      }
      if (Level != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Level);
      }
      if (DressAvatarId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(DressAvatarId);
      }
      if (UniqueId != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(UniqueId);
      }
      if (IsDiscarded != false) {
        output.WriteRawTag(104);
        output.WriteBool(IsDiscarded);
      }
      if (Exp != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(Exp);
      }
      if (IsProtected != false) {
        output.WriteRawTag(120);
        output.WriteBool(IsProtected);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Tid != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Tid);
      }
      subAffixList_.WriteTo(ref output, _repeated_subAffixList_codec);
      if (MainAffixId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(MainAffixId);
      }
      if (Level != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Level);
      }
      if (DressAvatarId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(DressAvatarId);
      }
      if (UniqueId != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(UniqueId);
      }
      if (IsDiscarded != false) {
        output.WriteRawTag(104);
        output.WriteBool(IsDiscarded);
      }
      if (Exp != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(Exp);
      }
      if (IsProtected != false) {
        output.WriteRawTag(120);
        output.WriteBool(IsProtected);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DressAvatarId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DressAvatarId);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Level);
      }
      if (MainAffixId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MainAffixId);
      }
      if (UniqueId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UniqueId);
      }
      if (Tid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Tid);
      }
      size += subAffixList_.CalculateSize(_repeated_subAffixList_codec);
      if (IsDiscarded != false) {
        size += 1 + 1;
      }
      if (Exp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Exp);
      }
      if (IsProtected != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Relic other) {
      if (other == null) {
        return;
      }
      if (other.DressAvatarId != 0) {
        DressAvatarId = other.DressAvatarId;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.MainAffixId != 0) {
        MainAffixId = other.MainAffixId;
      }
      if (other.UniqueId != 0) {
        UniqueId = other.UniqueId;
      }
      if (other.Tid != 0) {
        Tid = other.Tid;
      }
      subAffixList_.Add(other.subAffixList_);
      if (other.IsDiscarded != false) {
        IsDiscarded = other.IsDiscarded;
      }
      if (other.Exp != 0) {
        Exp = other.Exp;
      }
      if (other.IsProtected != false) {
        IsProtected = other.IsProtected;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Tid = input.ReadUInt32();
            break;
          }
          case 42: {
            subAffixList_.AddEntriesFrom(input, _repeated_subAffixList_codec);
            break;
          }
          case 48: {
            MainAffixId = input.ReadUInt32();
            break;
          }
          case 56: {
            Level = input.ReadUInt32();
            break;
          }
          case 64: {
            DressAvatarId = input.ReadUInt32();
            break;
          }
          case 88: {
            UniqueId = input.ReadUInt32();
            break;
          }
          case 104: {
            IsDiscarded = input.ReadBool();
            break;
          }
          case 112: {
            Exp = input.ReadUInt32();
            break;
          }
          case 120: {
            IsProtected = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Tid = input.ReadUInt32();
            break;
          }
          case 42: {
            subAffixList_.AddEntriesFrom(ref input, _repeated_subAffixList_codec);
            break;
          }
          case 48: {
            MainAffixId = input.ReadUInt32();
            break;
          }
          case 56: {
            Level = input.ReadUInt32();
            break;
          }
          case 64: {
            DressAvatarId = input.ReadUInt32();
            break;
          }
          case 88: {
            UniqueId = input.ReadUInt32();
            break;
          }
          case 104: {
            IsDiscarded = input.ReadBool();
            break;
          }
          case 112: {
            Exp = input.ReadUInt32();
            break;
          }
          case 120: {
            IsProtected = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
