// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: StartPunkLordRaidScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from StartPunkLordRaidScRsp.proto</summary>
  public static partial class StartPunkLordRaidScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for StartPunkLordRaidScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StartPunkLordRaidScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxTdGFydFB1bmtMb3JkUmFpZFNjUnNwLnByb3RvGhFDT0FMSEFGSVBORy5w",
            "cm90bxoRRE5MQkhBQ0VJQUwucHJvdG8iqAEKFlN0YXJ0UHVua0xvcmRSYWlk",
            "U2NSc3ASEwoLRE1FSUxKSkRLTEkYAyABKAMSEwoLR0JCQkxBSUVCRE4YCCAB",
            "KAgSDwoHcmV0Y29kZRgMIAEoDRITCgtORkNLRUFPSUxETRgFIAMoDRIbCgVz",
            "Y2VuZRgJIAEoCzIMLkROTEJIQUNFSUFMEiEKC0JQR0ZOQ05KS0hIGAQgASgL",
            "MgwuQ09BTEhBRklQTkdCHqoCG0VnZ0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90",
            "b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.COALHAFIPNGReflection.Descriptor, global::EggLink.DanhengServer.Proto.DNLBHACEIALReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.StartPunkLordRaidScRsp), global::EggLink.DanhengServer.Proto.StartPunkLordRaidScRsp.Parser, new[]{ "DMEILJJDKLI", "GBBBLAIEBDN", "Retcode", "NFCKEAOILDM", "Scene", "BPGFNCNJKHH" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class StartPunkLordRaidScRsp : pb::IMessage<StartPunkLordRaidScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StartPunkLordRaidScRsp> _parser = new pb::MessageParser<StartPunkLordRaidScRsp>(() => new StartPunkLordRaidScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StartPunkLordRaidScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.StartPunkLordRaidScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartPunkLordRaidScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartPunkLordRaidScRsp(StartPunkLordRaidScRsp other) : this() {
      dMEILJJDKLI_ = other.dMEILJJDKLI_;
      gBBBLAIEBDN_ = other.gBBBLAIEBDN_;
      retcode_ = other.retcode_;
      nFCKEAOILDM_ = other.nFCKEAOILDM_.Clone();
      scene_ = other.scene_ != null ? other.scene_.Clone() : null;
      bPGFNCNJKHH_ = other.bPGFNCNJKHH_ != null ? other.bPGFNCNJKHH_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StartPunkLordRaidScRsp Clone() {
      return new StartPunkLordRaidScRsp(this);
    }

    /// <summary>Field number for the "DMEILJJDKLI" field.</summary>
    public const int DMEILJJDKLIFieldNumber = 3;
    private long dMEILJJDKLI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DMEILJJDKLI {
      get { return dMEILJJDKLI_; }
      set {
        dMEILJJDKLI_ = value;
      }
    }

    /// <summary>Field number for the "GBBBLAIEBDN" field.</summary>
    public const int GBBBLAIEBDNFieldNumber = 8;
    private bool gBBBLAIEBDN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool GBBBLAIEBDN {
      get { return gBBBLAIEBDN_; }
      set {
        gBBBLAIEBDN_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 12;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "NFCKEAOILDM" field.</summary>
    public const int NFCKEAOILDMFieldNumber = 5;
    private static readonly pb::FieldCodec<uint> _repeated_nFCKEAOILDM_codec
        = pb::FieldCodec.ForUInt32(42);
    private readonly pbc::RepeatedField<uint> nFCKEAOILDM_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> NFCKEAOILDM {
      get { return nFCKEAOILDM_; }
    }

    /// <summary>Field number for the "scene" field.</summary>
    public const int SceneFieldNumber = 9;
    private global::EggLink.DanhengServer.Proto.DNLBHACEIAL scene_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.DNLBHACEIAL Scene {
      get { return scene_; }
      set {
        scene_ = value;
      }
    }

    /// <summary>Field number for the "BPGFNCNJKHH" field.</summary>
    public const int BPGFNCNJKHHFieldNumber = 4;
    private global::EggLink.DanhengServer.Proto.COALHAFIPNG bPGFNCNJKHH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.COALHAFIPNG BPGFNCNJKHH {
      get { return bPGFNCNJKHH_; }
      set {
        bPGFNCNJKHH_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StartPunkLordRaidScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StartPunkLordRaidScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DMEILJJDKLI != other.DMEILJJDKLI) return false;
      if (GBBBLAIEBDN != other.GBBBLAIEBDN) return false;
      if (Retcode != other.Retcode) return false;
      if(!nFCKEAOILDM_.Equals(other.nFCKEAOILDM_)) return false;
      if (!object.Equals(Scene, other.Scene)) return false;
      if (!object.Equals(BPGFNCNJKHH, other.BPGFNCNJKHH)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DMEILJJDKLI != 0L) hash ^= DMEILJJDKLI.GetHashCode();
      if (GBBBLAIEBDN != false) hash ^= GBBBLAIEBDN.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      hash ^= nFCKEAOILDM_.GetHashCode();
      if (scene_ != null) hash ^= Scene.GetHashCode();
      if (bPGFNCNJKHH_ != null) hash ^= BPGFNCNJKHH.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DMEILJJDKLI != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(DMEILJJDKLI);
      }
      if (bPGFNCNJKHH_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BPGFNCNJKHH);
      }
      nFCKEAOILDM_.WriteTo(output, _repeated_nFCKEAOILDM_codec);
      if (GBBBLAIEBDN != false) {
        output.WriteRawTag(64);
        output.WriteBool(GBBBLAIEBDN);
      }
      if (scene_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Scene);
      }
      if (Retcode != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DMEILJJDKLI != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(DMEILJJDKLI);
      }
      if (bPGFNCNJKHH_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BPGFNCNJKHH);
      }
      nFCKEAOILDM_.WriteTo(ref output, _repeated_nFCKEAOILDM_codec);
      if (GBBBLAIEBDN != false) {
        output.WriteRawTag(64);
        output.WriteBool(GBBBLAIEBDN);
      }
      if (scene_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Scene);
      }
      if (Retcode != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(Retcode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DMEILJJDKLI != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DMEILJJDKLI);
      }
      if (GBBBLAIEBDN != false) {
        size += 1 + 1;
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      size += nFCKEAOILDM_.CalculateSize(_repeated_nFCKEAOILDM_codec);
      if (scene_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Scene);
      }
      if (bPGFNCNJKHH_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BPGFNCNJKHH);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StartPunkLordRaidScRsp other) {
      if (other == null) {
        return;
      }
      if (other.DMEILJJDKLI != 0L) {
        DMEILJJDKLI = other.DMEILJJDKLI;
      }
      if (other.GBBBLAIEBDN != false) {
        GBBBLAIEBDN = other.GBBBLAIEBDN;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      nFCKEAOILDM_.Add(other.nFCKEAOILDM_);
      if (other.scene_ != null) {
        if (scene_ == null) {
          Scene = new global::EggLink.DanhengServer.Proto.DNLBHACEIAL();
        }
        Scene.MergeFrom(other.Scene);
      }
      if (other.bPGFNCNJKHH_ != null) {
        if (bPGFNCNJKHH_ == null) {
          BPGFNCNJKHH = new global::EggLink.DanhengServer.Proto.COALHAFIPNG();
        }
        BPGFNCNJKHH.MergeFrom(other.BPGFNCNJKHH);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            DMEILJJDKLI = input.ReadInt64();
            break;
          }
          case 34: {
            if (bPGFNCNJKHH_ == null) {
              BPGFNCNJKHH = new global::EggLink.DanhengServer.Proto.COALHAFIPNG();
            }
            input.ReadMessage(BPGFNCNJKHH);
            break;
          }
          case 42:
          case 40: {
            nFCKEAOILDM_.AddEntriesFrom(input, _repeated_nFCKEAOILDM_codec);
            break;
          }
          case 64: {
            GBBBLAIEBDN = input.ReadBool();
            break;
          }
          case 74: {
            if (scene_ == null) {
              Scene = new global::EggLink.DanhengServer.Proto.DNLBHACEIAL();
            }
            input.ReadMessage(Scene);
            break;
          }
          case 96: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            DMEILJJDKLI = input.ReadInt64();
            break;
          }
          case 34: {
            if (bPGFNCNJKHH_ == null) {
              BPGFNCNJKHH = new global::EggLink.DanhengServer.Proto.COALHAFIPNG();
            }
            input.ReadMessage(BPGFNCNJKHH);
            break;
          }
          case 42:
          case 40: {
            nFCKEAOILDM_.AddEntriesFrom(ref input, _repeated_nFCKEAOILDM_codec);
            break;
          }
          case 64: {
            GBBBLAIEBDN = input.ReadBool();
            break;
          }
          case 74: {
            if (scene_ == null) {
              Scene = new global::EggLink.DanhengServer.Proto.DNLBHACEIAL();
            }
            input.ReadMessage(Scene);
            break;
          }
          case 96: {
            Retcode = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
