// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TravelBrochureApplyPasterCsReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from TravelBrochureApplyPasterCsReq.proto</summary>
  public static partial class TravelBrochureApplyPasterCsReqReflection {

    #region Descriptor
    /// <summary>File descriptor for TravelBrochureApplyPasterCsReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TravelBrochureApplyPasterCsReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRUcmF2ZWxCcm9jaHVyZUFwcGx5UGFzdGVyQ3NSZXEucHJvdG8imgEKHlRy",
            "YXZlbEJyb2NodXJlQXBwbHlQYXN0ZXJDc1JlcRITCgtMR0pIT09ERU5QTRgI",
            "IAEoDRITCgtOUEhJTEJHSUJOTRgGIAEoBRITCgtBRktGSkRKQkVQQRgFIAEo",
            "BRITCgtPS0pQRk5HTExNSRgJIAEoDRIPCgdpdGVtX2lkGAQgASgNEhMKC01G",
            "SkxMS09PRkJMGAcgASgNQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJv",
            "dG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.TravelBrochureApplyPasterCsReq), global::EggLink.DanhengServer.Proto.TravelBrochureApplyPasterCsReq.Parser, new[]{ "LGJHOODENPM", "NPHILBGIBNM", "AFKFJDJBEPA", "OKJPFNGLLMI", "ItemId", "MFJLLKOOFBL" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TravelBrochureApplyPasterCsReq : pb::IMessage<TravelBrochureApplyPasterCsReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TravelBrochureApplyPasterCsReq> _parser = new pb::MessageParser<TravelBrochureApplyPasterCsReq>(() => new TravelBrochureApplyPasterCsReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TravelBrochureApplyPasterCsReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.TravelBrochureApplyPasterCsReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TravelBrochureApplyPasterCsReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TravelBrochureApplyPasterCsReq(TravelBrochureApplyPasterCsReq other) : this() {
      lGJHOODENPM_ = other.lGJHOODENPM_;
      nPHILBGIBNM_ = other.nPHILBGIBNM_;
      aFKFJDJBEPA_ = other.aFKFJDJBEPA_;
      oKJPFNGLLMI_ = other.oKJPFNGLLMI_;
      itemId_ = other.itemId_;
      mFJLLKOOFBL_ = other.mFJLLKOOFBL_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TravelBrochureApplyPasterCsReq Clone() {
      return new TravelBrochureApplyPasterCsReq(this);
    }

    /// <summary>Field number for the "LGJHOODENPM" field.</summary>
    public const int LGJHOODENPMFieldNumber = 8;
    private uint lGJHOODENPM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LGJHOODENPM {
      get { return lGJHOODENPM_; }
      set {
        lGJHOODENPM_ = value;
      }
    }

    /// <summary>Field number for the "NPHILBGIBNM" field.</summary>
    public const int NPHILBGIBNMFieldNumber = 6;
    private int nPHILBGIBNM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NPHILBGIBNM {
      get { return nPHILBGIBNM_; }
      set {
        nPHILBGIBNM_ = value;
      }
    }

    /// <summary>Field number for the "AFKFJDJBEPA" field.</summary>
    public const int AFKFJDJBEPAFieldNumber = 5;
    private int aFKFJDJBEPA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AFKFJDJBEPA {
      get { return aFKFJDJBEPA_; }
      set {
        aFKFJDJBEPA_ = value;
      }
    }

    /// <summary>Field number for the "OKJPFNGLLMI" field.</summary>
    public const int OKJPFNGLLMIFieldNumber = 9;
    private uint oKJPFNGLLMI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint OKJPFNGLLMI {
      get { return oKJPFNGLLMI_; }
      set {
        oKJPFNGLLMI_ = value;
      }
    }

    /// <summary>Field number for the "item_id" field.</summary>
    public const int ItemIdFieldNumber = 4;
    private uint itemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    /// <summary>Field number for the "MFJLLKOOFBL" field.</summary>
    public const int MFJLLKOOFBLFieldNumber = 7;
    private uint mFJLLKOOFBL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MFJLLKOOFBL {
      get { return mFJLLKOOFBL_; }
      set {
        mFJLLKOOFBL_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TravelBrochureApplyPasterCsReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TravelBrochureApplyPasterCsReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LGJHOODENPM != other.LGJHOODENPM) return false;
      if (NPHILBGIBNM != other.NPHILBGIBNM) return false;
      if (AFKFJDJBEPA != other.AFKFJDJBEPA) return false;
      if (OKJPFNGLLMI != other.OKJPFNGLLMI) return false;
      if (ItemId != other.ItemId) return false;
      if (MFJLLKOOFBL != other.MFJLLKOOFBL) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LGJHOODENPM != 0) hash ^= LGJHOODENPM.GetHashCode();
      if (NPHILBGIBNM != 0) hash ^= NPHILBGIBNM.GetHashCode();
      if (AFKFJDJBEPA != 0) hash ^= AFKFJDJBEPA.GetHashCode();
      if (OKJPFNGLLMI != 0) hash ^= OKJPFNGLLMI.GetHashCode();
      if (ItemId != 0) hash ^= ItemId.GetHashCode();
      if (MFJLLKOOFBL != 0) hash ^= MFJLLKOOFBL.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ItemId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(ItemId);
      }
      if (AFKFJDJBEPA != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AFKFJDJBEPA);
      }
      if (NPHILBGIBNM != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NPHILBGIBNM);
      }
      if (MFJLLKOOFBL != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(MFJLLKOOFBL);
      }
      if (LGJHOODENPM != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(LGJHOODENPM);
      }
      if (OKJPFNGLLMI != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(OKJPFNGLLMI);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ItemId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(ItemId);
      }
      if (AFKFJDJBEPA != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AFKFJDJBEPA);
      }
      if (NPHILBGIBNM != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NPHILBGIBNM);
      }
      if (MFJLLKOOFBL != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(MFJLLKOOFBL);
      }
      if (LGJHOODENPM != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(LGJHOODENPM);
      }
      if (OKJPFNGLLMI != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(OKJPFNGLLMI);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LGJHOODENPM != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LGJHOODENPM);
      }
      if (NPHILBGIBNM != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NPHILBGIBNM);
      }
      if (AFKFJDJBEPA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AFKFJDJBEPA);
      }
      if (OKJPFNGLLMI != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OKJPFNGLLMI);
      }
      if (ItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ItemId);
      }
      if (MFJLLKOOFBL != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MFJLLKOOFBL);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TravelBrochureApplyPasterCsReq other) {
      if (other == null) {
        return;
      }
      if (other.LGJHOODENPM != 0) {
        LGJHOODENPM = other.LGJHOODENPM;
      }
      if (other.NPHILBGIBNM != 0) {
        NPHILBGIBNM = other.NPHILBGIBNM;
      }
      if (other.AFKFJDJBEPA != 0) {
        AFKFJDJBEPA = other.AFKFJDJBEPA;
      }
      if (other.OKJPFNGLLMI != 0) {
        OKJPFNGLLMI = other.OKJPFNGLLMI;
      }
      if (other.ItemId != 0) {
        ItemId = other.ItemId;
      }
      if (other.MFJLLKOOFBL != 0) {
        MFJLLKOOFBL = other.MFJLLKOOFBL;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 32: {
            ItemId = input.ReadUInt32();
            break;
          }
          case 40: {
            AFKFJDJBEPA = input.ReadInt32();
            break;
          }
          case 48: {
            NPHILBGIBNM = input.ReadInt32();
            break;
          }
          case 56: {
            MFJLLKOOFBL = input.ReadUInt32();
            break;
          }
          case 64: {
            LGJHOODENPM = input.ReadUInt32();
            break;
          }
          case 72: {
            OKJPFNGLLMI = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 32: {
            ItemId = input.ReadUInt32();
            break;
          }
          case 40: {
            AFKFJDJBEPA = input.ReadInt32();
            break;
          }
          case 48: {
            NPHILBGIBNM = input.ReadInt32();
            break;
          }
          case 56: {
            MFJLLKOOFBL = input.ReadUInt32();
            break;
          }
          case 64: {
            LGJHOODENPM = input.ReadUInt32();
            break;
          }
          case 72: {
            OKJPFNGLLMI = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
