// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UpdatePlayerSetting.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from UpdatePlayerSetting.proto</summary>
  public static partial class UpdatePlayerSettingReflection {

    #region Descriptor
    /// <summary>File descriptor for UpdatePlayerSetting.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UpdatePlayerSettingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlVcGRhdGVQbGF5ZXJTZXR0aW5nLnByb3RvIpUCChNVcGRhdGVQbGF5ZXJT",
            "ZXR0aW5nEhUKC01FRkZLQ0FQQkZKGA0gASgISAASFQoLS09GREVPQUdMR0sY",
            "DCABKAhIABIVCgtERU5GTEpLSE5GTxgIIAEoCEgAEhUKC0tIS0FBUEFDR0pG",
            "GAcgASgISAASFQoLS0tISENPUEVOR00YBiABKAhIABIVCgtLTUNDS0lNSEJC",
            "ShgLIAEoCEgAEhUKC09JR0lQTUVPRUtCGAEgASgISAASFQoLS01BQ0RNQUZG",
            "Rk4YDyABKAhIABIVCgtFRkNDRERNTk1MUBgCIAEoCEgAEh8KFWluY2x1ZGVf",
            "dXBncmFkZV9yZWxpYxgKIAEoCEgAQg4KDHNldHRpbmdfY2FzZUIeqgIbRWdn",
            "TGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.UpdatePlayerSetting), global::EggLink.DanhengServer.Proto.UpdatePlayerSetting.Parser, new[]{ "MEFFKCAPBFJ", "KOFDEOAGLGK", "DENFLJKHNFO", "KHKAAPACGJF", "KKHHCOPENGM", "KMCCKIMHBBJ", "OIGIPMEOEKB", "KMACDMAFFFN", "EFCCDDMNMLP", "IncludeUpgradeRelic" }, new[]{ "SettingCase" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdatePlayerSetting : pb::IMessage<UpdatePlayerSetting>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdatePlayerSetting> _parser = new pb::MessageParser<UpdatePlayerSetting>(() => new UpdatePlayerSetting());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdatePlayerSetting> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.UpdatePlayerSettingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdatePlayerSetting() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdatePlayerSetting(UpdatePlayerSetting other) : this() {
      switch (other.SettingCaseCase) {
        case SettingCaseOneofCase.MEFFKCAPBFJ:
          MEFFKCAPBFJ = other.MEFFKCAPBFJ;
          break;
        case SettingCaseOneofCase.KOFDEOAGLGK:
          KOFDEOAGLGK = other.KOFDEOAGLGK;
          break;
        case SettingCaseOneofCase.DENFLJKHNFO:
          DENFLJKHNFO = other.DENFLJKHNFO;
          break;
        case SettingCaseOneofCase.KHKAAPACGJF:
          KHKAAPACGJF = other.KHKAAPACGJF;
          break;
        case SettingCaseOneofCase.KKHHCOPENGM:
          KKHHCOPENGM = other.KKHHCOPENGM;
          break;
        case SettingCaseOneofCase.KMCCKIMHBBJ:
          KMCCKIMHBBJ = other.KMCCKIMHBBJ;
          break;
        case SettingCaseOneofCase.OIGIPMEOEKB:
          OIGIPMEOEKB = other.OIGIPMEOEKB;
          break;
        case SettingCaseOneofCase.KMACDMAFFFN:
          KMACDMAFFFN = other.KMACDMAFFFN;
          break;
        case SettingCaseOneofCase.EFCCDDMNMLP:
          EFCCDDMNMLP = other.EFCCDDMNMLP;
          break;
        case SettingCaseOneofCase.IncludeUpgradeRelic:
          IncludeUpgradeRelic = other.IncludeUpgradeRelic;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdatePlayerSetting Clone() {
      return new UpdatePlayerSetting(this);
    }

    /// <summary>Field number for the "MEFFKCAPBFJ" field.</summary>
    public const int MEFFKCAPBFJFieldNumber = 13;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MEFFKCAPBFJ {
      get { return HasMEFFKCAPBFJ ? (bool) settingCase_ : false; }
      set {
        settingCase_ = value;
        settingCaseCase_ = SettingCaseOneofCase.MEFFKCAPBFJ;
      }
    }
    /// <summary>Gets whether the "MEFFKCAPBFJ" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMEFFKCAPBFJ {
      get { return settingCaseCase_ == SettingCaseOneofCase.MEFFKCAPBFJ; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "MEFFKCAPBFJ" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMEFFKCAPBFJ() {
      if (HasMEFFKCAPBFJ) {
        ClearSettingCase();
      }
    }

    /// <summary>Field number for the "KOFDEOAGLGK" field.</summary>
    public const int KOFDEOAGLGKFieldNumber = 12;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool KOFDEOAGLGK {
      get { return HasKOFDEOAGLGK ? (bool) settingCase_ : false; }
      set {
        settingCase_ = value;
        settingCaseCase_ = SettingCaseOneofCase.KOFDEOAGLGK;
      }
    }
    /// <summary>Gets whether the "KOFDEOAGLGK" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKOFDEOAGLGK {
      get { return settingCaseCase_ == SettingCaseOneofCase.KOFDEOAGLGK; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "KOFDEOAGLGK" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKOFDEOAGLGK() {
      if (HasKOFDEOAGLGK) {
        ClearSettingCase();
      }
    }

    /// <summary>Field number for the "DENFLJKHNFO" field.</summary>
    public const int DENFLJKHNFOFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DENFLJKHNFO {
      get { return HasDENFLJKHNFO ? (bool) settingCase_ : false; }
      set {
        settingCase_ = value;
        settingCaseCase_ = SettingCaseOneofCase.DENFLJKHNFO;
      }
    }
    /// <summary>Gets whether the "DENFLJKHNFO" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDENFLJKHNFO {
      get { return settingCaseCase_ == SettingCaseOneofCase.DENFLJKHNFO; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "DENFLJKHNFO" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDENFLJKHNFO() {
      if (HasDENFLJKHNFO) {
        ClearSettingCase();
      }
    }

    /// <summary>Field number for the "KHKAAPACGJF" field.</summary>
    public const int KHKAAPACGJFFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool KHKAAPACGJF {
      get { return HasKHKAAPACGJF ? (bool) settingCase_ : false; }
      set {
        settingCase_ = value;
        settingCaseCase_ = SettingCaseOneofCase.KHKAAPACGJF;
      }
    }
    /// <summary>Gets whether the "KHKAAPACGJF" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKHKAAPACGJF {
      get { return settingCaseCase_ == SettingCaseOneofCase.KHKAAPACGJF; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "KHKAAPACGJF" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKHKAAPACGJF() {
      if (HasKHKAAPACGJF) {
        ClearSettingCase();
      }
    }

    /// <summary>Field number for the "KKHHCOPENGM" field.</summary>
    public const int KKHHCOPENGMFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool KKHHCOPENGM {
      get { return HasKKHHCOPENGM ? (bool) settingCase_ : false; }
      set {
        settingCase_ = value;
        settingCaseCase_ = SettingCaseOneofCase.KKHHCOPENGM;
      }
    }
    /// <summary>Gets whether the "KKHHCOPENGM" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKKHHCOPENGM {
      get { return settingCaseCase_ == SettingCaseOneofCase.KKHHCOPENGM; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "KKHHCOPENGM" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKKHHCOPENGM() {
      if (HasKKHHCOPENGM) {
        ClearSettingCase();
      }
    }

    /// <summary>Field number for the "KMCCKIMHBBJ" field.</summary>
    public const int KMCCKIMHBBJFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool KMCCKIMHBBJ {
      get { return HasKMCCKIMHBBJ ? (bool) settingCase_ : false; }
      set {
        settingCase_ = value;
        settingCaseCase_ = SettingCaseOneofCase.KMCCKIMHBBJ;
      }
    }
    /// <summary>Gets whether the "KMCCKIMHBBJ" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKMCCKIMHBBJ {
      get { return settingCaseCase_ == SettingCaseOneofCase.KMCCKIMHBBJ; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "KMCCKIMHBBJ" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKMCCKIMHBBJ() {
      if (HasKMCCKIMHBBJ) {
        ClearSettingCase();
      }
    }

    /// <summary>Field number for the "OIGIPMEOEKB" field.</summary>
    public const int OIGIPMEOEKBFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OIGIPMEOEKB {
      get { return HasOIGIPMEOEKB ? (bool) settingCase_ : false; }
      set {
        settingCase_ = value;
        settingCaseCase_ = SettingCaseOneofCase.OIGIPMEOEKB;
      }
    }
    /// <summary>Gets whether the "OIGIPMEOEKB" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOIGIPMEOEKB {
      get { return settingCaseCase_ == SettingCaseOneofCase.OIGIPMEOEKB; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "OIGIPMEOEKB" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOIGIPMEOEKB() {
      if (HasOIGIPMEOEKB) {
        ClearSettingCase();
      }
    }

    /// <summary>Field number for the "KMACDMAFFFN" field.</summary>
    public const int KMACDMAFFFNFieldNumber = 15;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool KMACDMAFFFN {
      get { return HasKMACDMAFFFN ? (bool) settingCase_ : false; }
      set {
        settingCase_ = value;
        settingCaseCase_ = SettingCaseOneofCase.KMACDMAFFFN;
      }
    }
    /// <summary>Gets whether the "KMACDMAFFFN" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKMACDMAFFFN {
      get { return settingCaseCase_ == SettingCaseOneofCase.KMACDMAFFFN; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "KMACDMAFFFN" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKMACDMAFFFN() {
      if (HasKMACDMAFFFN) {
        ClearSettingCase();
      }
    }

    /// <summary>Field number for the "EFCCDDMNMLP" field.</summary>
    public const int EFCCDDMNMLPFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EFCCDDMNMLP {
      get { return HasEFCCDDMNMLP ? (bool) settingCase_ : false; }
      set {
        settingCase_ = value;
        settingCaseCase_ = SettingCaseOneofCase.EFCCDDMNMLP;
      }
    }
    /// <summary>Gets whether the "EFCCDDMNMLP" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEFCCDDMNMLP {
      get { return settingCaseCase_ == SettingCaseOneofCase.EFCCDDMNMLP; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "EFCCDDMNMLP" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEFCCDDMNMLP() {
      if (HasEFCCDDMNMLP) {
        ClearSettingCase();
      }
    }

    /// <summary>Field number for the "include_upgrade_relic" field.</summary>
    public const int IncludeUpgradeRelicFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IncludeUpgradeRelic {
      get { return HasIncludeUpgradeRelic ? (bool) settingCase_ : false; }
      set {
        settingCase_ = value;
        settingCaseCase_ = SettingCaseOneofCase.IncludeUpgradeRelic;
      }
    }
    /// <summary>Gets whether the "include_upgrade_relic" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIncludeUpgradeRelic {
      get { return settingCaseCase_ == SettingCaseOneofCase.IncludeUpgradeRelic; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "include_upgrade_relic" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIncludeUpgradeRelic() {
      if (HasIncludeUpgradeRelic) {
        ClearSettingCase();
      }
    }

    private object settingCase_;
    /// <summary>Enum of possible cases for the "setting_case" oneof.</summary>
    public enum SettingCaseOneofCase {
      None = 0,
      MEFFKCAPBFJ = 13,
      KOFDEOAGLGK = 12,
      DENFLJKHNFO = 8,
      KHKAAPACGJF = 7,
      KKHHCOPENGM = 6,
      KMCCKIMHBBJ = 11,
      OIGIPMEOEKB = 1,
      KMACDMAFFFN = 15,
      EFCCDDMNMLP = 2,
      IncludeUpgradeRelic = 10,
    }
    private SettingCaseOneofCase settingCaseCase_ = SettingCaseOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SettingCaseOneofCase SettingCaseCase {
      get { return settingCaseCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSettingCase() {
      settingCaseCase_ = SettingCaseOneofCase.None;
      settingCase_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdatePlayerSetting);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdatePlayerSetting other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MEFFKCAPBFJ != other.MEFFKCAPBFJ) return false;
      if (KOFDEOAGLGK != other.KOFDEOAGLGK) return false;
      if (DENFLJKHNFO != other.DENFLJKHNFO) return false;
      if (KHKAAPACGJF != other.KHKAAPACGJF) return false;
      if (KKHHCOPENGM != other.KKHHCOPENGM) return false;
      if (KMCCKIMHBBJ != other.KMCCKIMHBBJ) return false;
      if (OIGIPMEOEKB != other.OIGIPMEOEKB) return false;
      if (KMACDMAFFFN != other.KMACDMAFFFN) return false;
      if (EFCCDDMNMLP != other.EFCCDDMNMLP) return false;
      if (IncludeUpgradeRelic != other.IncludeUpgradeRelic) return false;
      if (SettingCaseCase != other.SettingCaseCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasMEFFKCAPBFJ) hash ^= MEFFKCAPBFJ.GetHashCode();
      if (HasKOFDEOAGLGK) hash ^= KOFDEOAGLGK.GetHashCode();
      if (HasDENFLJKHNFO) hash ^= DENFLJKHNFO.GetHashCode();
      if (HasKHKAAPACGJF) hash ^= KHKAAPACGJF.GetHashCode();
      if (HasKKHHCOPENGM) hash ^= KKHHCOPENGM.GetHashCode();
      if (HasKMCCKIMHBBJ) hash ^= KMCCKIMHBBJ.GetHashCode();
      if (HasOIGIPMEOEKB) hash ^= OIGIPMEOEKB.GetHashCode();
      if (HasKMACDMAFFFN) hash ^= KMACDMAFFFN.GetHashCode();
      if (HasEFCCDDMNMLP) hash ^= EFCCDDMNMLP.GetHashCode();
      if (HasIncludeUpgradeRelic) hash ^= IncludeUpgradeRelic.GetHashCode();
      hash ^= (int) settingCaseCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasOIGIPMEOEKB) {
        output.WriteRawTag(8);
        output.WriteBool(OIGIPMEOEKB);
      }
      if (HasEFCCDDMNMLP) {
        output.WriteRawTag(16);
        output.WriteBool(EFCCDDMNMLP);
      }
      if (HasKKHHCOPENGM) {
        output.WriteRawTag(48);
        output.WriteBool(KKHHCOPENGM);
      }
      if (HasKHKAAPACGJF) {
        output.WriteRawTag(56);
        output.WriteBool(KHKAAPACGJF);
      }
      if (HasDENFLJKHNFO) {
        output.WriteRawTag(64);
        output.WriteBool(DENFLJKHNFO);
      }
      if (HasIncludeUpgradeRelic) {
        output.WriteRawTag(80);
        output.WriteBool(IncludeUpgradeRelic);
      }
      if (HasKMCCKIMHBBJ) {
        output.WriteRawTag(88);
        output.WriteBool(KMCCKIMHBBJ);
      }
      if (HasKOFDEOAGLGK) {
        output.WriteRawTag(96);
        output.WriteBool(KOFDEOAGLGK);
      }
      if (HasMEFFKCAPBFJ) {
        output.WriteRawTag(104);
        output.WriteBool(MEFFKCAPBFJ);
      }
      if (HasKMACDMAFFFN) {
        output.WriteRawTag(120);
        output.WriteBool(KMACDMAFFFN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasOIGIPMEOEKB) {
        output.WriteRawTag(8);
        output.WriteBool(OIGIPMEOEKB);
      }
      if (HasEFCCDDMNMLP) {
        output.WriteRawTag(16);
        output.WriteBool(EFCCDDMNMLP);
      }
      if (HasKKHHCOPENGM) {
        output.WriteRawTag(48);
        output.WriteBool(KKHHCOPENGM);
      }
      if (HasKHKAAPACGJF) {
        output.WriteRawTag(56);
        output.WriteBool(KHKAAPACGJF);
      }
      if (HasDENFLJKHNFO) {
        output.WriteRawTag(64);
        output.WriteBool(DENFLJKHNFO);
      }
      if (HasIncludeUpgradeRelic) {
        output.WriteRawTag(80);
        output.WriteBool(IncludeUpgradeRelic);
      }
      if (HasKMCCKIMHBBJ) {
        output.WriteRawTag(88);
        output.WriteBool(KMCCKIMHBBJ);
      }
      if (HasKOFDEOAGLGK) {
        output.WriteRawTag(96);
        output.WriteBool(KOFDEOAGLGK);
      }
      if (HasMEFFKCAPBFJ) {
        output.WriteRawTag(104);
        output.WriteBool(MEFFKCAPBFJ);
      }
      if (HasKMACDMAFFFN) {
        output.WriteRawTag(120);
        output.WriteBool(KMACDMAFFFN);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasMEFFKCAPBFJ) {
        size += 1 + 1;
      }
      if (HasKOFDEOAGLGK) {
        size += 1 + 1;
      }
      if (HasDENFLJKHNFO) {
        size += 1 + 1;
      }
      if (HasKHKAAPACGJF) {
        size += 1 + 1;
      }
      if (HasKKHHCOPENGM) {
        size += 1 + 1;
      }
      if (HasKMCCKIMHBBJ) {
        size += 1 + 1;
      }
      if (HasOIGIPMEOEKB) {
        size += 1 + 1;
      }
      if (HasKMACDMAFFFN) {
        size += 1 + 1;
      }
      if (HasEFCCDDMNMLP) {
        size += 1 + 1;
      }
      if (HasIncludeUpgradeRelic) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdatePlayerSetting other) {
      if (other == null) {
        return;
      }
      switch (other.SettingCaseCase) {
        case SettingCaseOneofCase.MEFFKCAPBFJ:
          MEFFKCAPBFJ = other.MEFFKCAPBFJ;
          break;
        case SettingCaseOneofCase.KOFDEOAGLGK:
          KOFDEOAGLGK = other.KOFDEOAGLGK;
          break;
        case SettingCaseOneofCase.DENFLJKHNFO:
          DENFLJKHNFO = other.DENFLJKHNFO;
          break;
        case SettingCaseOneofCase.KHKAAPACGJF:
          KHKAAPACGJF = other.KHKAAPACGJF;
          break;
        case SettingCaseOneofCase.KKHHCOPENGM:
          KKHHCOPENGM = other.KKHHCOPENGM;
          break;
        case SettingCaseOneofCase.KMCCKIMHBBJ:
          KMCCKIMHBBJ = other.KMCCKIMHBBJ;
          break;
        case SettingCaseOneofCase.OIGIPMEOEKB:
          OIGIPMEOEKB = other.OIGIPMEOEKB;
          break;
        case SettingCaseOneofCase.KMACDMAFFFN:
          KMACDMAFFFN = other.KMACDMAFFFN;
          break;
        case SettingCaseOneofCase.EFCCDDMNMLP:
          EFCCDDMNMLP = other.EFCCDDMNMLP;
          break;
        case SettingCaseOneofCase.IncludeUpgradeRelic:
          IncludeUpgradeRelic = other.IncludeUpgradeRelic;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OIGIPMEOEKB = input.ReadBool();
            break;
          }
          case 16: {
            EFCCDDMNMLP = input.ReadBool();
            break;
          }
          case 48: {
            KKHHCOPENGM = input.ReadBool();
            break;
          }
          case 56: {
            KHKAAPACGJF = input.ReadBool();
            break;
          }
          case 64: {
            DENFLJKHNFO = input.ReadBool();
            break;
          }
          case 80: {
            IncludeUpgradeRelic = input.ReadBool();
            break;
          }
          case 88: {
            KMCCKIMHBBJ = input.ReadBool();
            break;
          }
          case 96: {
            KOFDEOAGLGK = input.ReadBool();
            break;
          }
          case 104: {
            MEFFKCAPBFJ = input.ReadBool();
            break;
          }
          case 120: {
            KMACDMAFFFN = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OIGIPMEOEKB = input.ReadBool();
            break;
          }
          case 16: {
            EFCCDDMNMLP = input.ReadBool();
            break;
          }
          case 48: {
            KKHHCOPENGM = input.ReadBool();
            break;
          }
          case 56: {
            KHKAAPACGJF = input.ReadBool();
            break;
          }
          case 64: {
            DENFLJKHNFO = input.ReadBool();
            break;
          }
          case 80: {
            IncludeUpgradeRelic = input.ReadBool();
            break;
          }
          case 88: {
            KMCCKIMHBBJ = input.ReadBool();
            break;
          }
          case 96: {
            KOFDEOAGLGK = input.ReadBool();
            break;
          }
          case 104: {
            MEFFKCAPBFJ = input.ReadBool();
            break;
          }
          case 120: {
            KMACDMAFFFN = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
